//··························································
// Copyright (c) 2023-2026. Jonathan Bédard ~ JóôòKiwi
//
// This project is free to use.
// All the right is reserved to the author of this project.
// My projects:
//  - https://github.com/joooKiwi/type
//  - https://github.com/joooKiwi/lazy
//  - https://github.com/joooKiwi/collection
//  - https://github.com/joooKiwi/enumeration
//··························································

import type {CollectionHolder}      from "../CollectionHolder"
import type {KeyOfCollectionHolder} from "../type/keyOf"

/**
 * Tell that the value has the structure of a {@link CollectionHolder}
 *
 * @param value The value to identify
 * @see isCollectionHolder
 * @see CollectionConstants.COLLECTION_MEMBERS
 * @doesNotValidateTheTypes
 */
export function isCollectionHolderByStructure(value: unknown,): value is (& object & Record<KeyOfCollectionHolder, unknown>)
/**
 * Tell that the value has the structure of a {@link CollectionHolder}
 *
 * @param value The value to identify
 * @see isCollectionHolder
 * @see CollectionConstants.COLLECTION_MEMBERS
 * @doesNotValidateTheTypes
 * @note Giving a type to the method is only here to help the implementation, but it will not change the behaviour in JavaScript
 */
export function isCollectionHolderByStructure<const T, const INSTANCE extends CollectionHolder<T> = CollectionHolder<T>, >(value: unknown,): value is INSTANCE
export function isCollectionHolderByStructure(value: unknown,) {
    if (value == null)
        return false
    if (typeof value != "object")
        return false
    if ("size" in value)
    if ("length" in value)
    if ("count" in value)
    if ("isEmpty" in value)
    if ("hasAtLeast1Element" in value)
    if ("includesAtLeast1Element" in value)
    if ("containsAtLeast1Element" in value)
    if ("hasExactly1Element" in value)
    if ("includesExactly1Element" in value)
    if ("containsExactly1Element" in value)
    if ("hasAtMost1Element" in value)
    if ("includesAtMost1Element" in value)
    if ("containsAtMost1Element" in value)
    if ("hasAtLeast2Elements" in value)
    if ("includesAtLeast2Elements" in value)
    if ("containsAtLeast2Elements" in value)
    if ("hasExactly2Elements" in value)
    if ("includesExactly2Elements" in value)
    if ("containsExactly2Elements" in value)
    if ("hasAtMost2Elements" in value)
    if ("includesAtMost2Elements" in value)
    if ("containsAtMost2Elements" in value)
    if ("get" in value)
    if ("at" in value)
    if ("elementAt" in value)
    if ("getFirst" in value)
    if ("getLast" in value)
    if ("getOrElse" in value)
    if ("atOrElse" in value)
    if ("elementAtOrElse" in value)
    if ("getFirstOrElse" in value)
    if ("getLastOrElse" in value)
    if ("getOrNull" in value)
    if ("atOrNull" in value)
    if ("elementAtOrNull" in value)
    if ("getFirstOrNull" in value)
    if ("getLastOrNull" in value)
    if ("first" in value)
    if ("firstOrNull" in value)
    if ("firstIndexed" in value)
    if ("firstIndexedOrNull" in value)
    if ("last" in value)
    if ("lastOrNull" in value)
    if ("lastIndexed" in value)
    if ("lastIndexedOrNull" in value)
    if ("findFirst" in value)
    if ("find" in value)
    if ("findFirstOrNull" in value)
    if ("findOrNull" in value)
    if ("findFirstIndexed" in value)
    if ("findIndexed" in value)
    if ("findFirstIndexedOrNull" in value)
    if ("findIndexedOrNull" in value)
    if ("findLast" in value)
    if ("findLastOrNull" in value)
    if ("findLastIndexed" in value)
    if ("findLastIndexedOrNull" in value)
    if ("firstIndexOf" in value)
    if ("indexOf" in value)
    if ("firstIndexOfOrNull" in value)
    if ("indexOfOrNull" in value)
    if ("lastIndexOf" in value)
    if ("lastIndexOfOrNull" in value)
    if ("indexOfFirst" in value)
    if ("findIndex" in value)
    if ("findFirstIndex" in value)
    if ("indexOfFirstOrNull" in value)
    if ("findIndexOrNull" in value)
    if ("findFirstIndexOrNull" in value)
    if ("indexOfFirstIndexed" in value)
    if ("findIndexIndexed" in value)
    if ("findFirstIndexIndexed" in value)
    if ("indexOfFirstIndexedOrNull" in value)
    if ("findIndexIndexedOrNull" in value)
    if ("findFirstIndexIndexedOrNull" in value)
    if ("indexOfLast" in value)
    if ("findLastIndex" in value)
    if ("indexOfLastOrNull" in value)
    if ("findLastIndexOrNull" in value)
    if ("indexOfLastIndexed" in value)
    if ("findLastIndexIndexed" in value)
    if ("indexOfLastIndexedOrNull" in value)
    if ("findLastIndexIndexedOrNull" in value)
    if ("all" in value)
    if ("every" in value)
    if ("any" in value)
    if ("some" in value)
    if ("none" in value)
    if ("hasNull" in value)
    if ("includesNull" in value)
    if ("containsNull" in value)
    if ("hasNoNulls" in value)
    if ("includesNoNulls" in value)
    if ("containsNoNulls" in value)
    if ("hasDuplicate" in value)
    if ("includesDuplicate" in value)
    if ("containsDuplicate" in value)
    if ("hasNoDuplicates" in value)
    if ("includesNoDuplicates" in value)
    if ("containsNoDuplicates" in value)
    if ("has" in value)
    if ("includes" in value)
    if ("contains" in value)
    if ("hasNot" in value)
    if ("includesNot" in value)
    if ("containsNot" in value)
    if ("hasOne" in value)
    if ("includesOne" in value)
    if ("containsOne" in value)
    if ("hasNotOne" in value)
    if ("includesNotOne" in value)
    if ("containsNotOne" in value)
    if ("hasAll" in value)
    if ("includesAll" in value)
    if ("containsAll" in value)
    if ("hasNotAll" in value)
    if ("includesNotAll" in value)
    if ("containsNotAll" in value)
    if ("requireNoNulls" in value)
    if ("filter" in value)
    if ("filterIndexed" in value)
    if ("filterNot" in value)
    if ("filterNotIndexed" in value)
    if ("slice" in value)
    if ("take" in value)
    if ("limit" in value)
    if ("takeWhile" in value)
    if ("limitWhile" in value)
    if ("takeWhileIndexed" in value)
    if ("limitWhileIndexed" in value)
    if ("takeLast" in value)
    if ("limitLast" in value)
    if ("takeLastWhile" in value)
    if ("limitLastWhile" in value)
    if ("takeLastWhileIndexed" in value)
    if ("limitLastWhileIndexed" in value)
    if ("drop" in value)
    if ("skip" in value)
    if ("dropWhile" in value)
    if ("skipWhile" in value)
    if ("dropWhileIndexed" in value)
    if ("skipWhileIndexed" in value)
    if ("dropLast" in value)
    if ("skipLast" in value)
    if ("dropLastWhile" in value)
    if ("skipLastWhile" in value)
    if ("dropLastWhileIndexed" in value)
    if ("skipLastWhileIndexed" in value)
    if ("map" in value)
    if ("mapIndexed" in value)
    if ("mapNotNull" in value)
    if ("mapNotNullIndexed" in value)
    if ("forEach" in value)
    if ("forEachIndexed" in value)
    if ("onEach" in value)
    if ("onEachIndexed" in value)
    if ("toReverse" in value)
    if ("toReversed" in value)
    if ("reversed" in value)
    if (Symbol.iterator in value)
    if (Symbol.toStringTag in value)
    if ("toIterator" in value)
    if ("toArray" in value)
    if ("toMutableArray" in value)
    if ("toSet" in value)
    if ("toMutableSet" in value)
    if ("toMap" in value)
    if ("toMutableMap" in value)
    if ("toString" in value)
    if ("toLocaleString" in value)
    if ("toLowerCaseString" in value)
    if ("toLocaleLowerCaseString" in value)
    if ("toUpperCaseString" in value)
    if ("toLocaleUpperCaseString" in value)
    if ("joinToString" in value)
    if ("join" in value)
        return true
    return false
}
