//··························································
// Copyright (c) 2023-2026. Jonathan Bédard ~ JóôòKiwi
//
// This project is free to use.
// All the right is reserved to the author of this project.
// My projects:
//  - https://github.com/joooKiwi/type
//  - https://github.com/joooKiwi/lazy
//  - https://github.com/joooKiwi/collection
//  - https://github.com/joooKiwi/enumeration
//··························································

import {A, AB, ABC, ABCD, EMPTY}                from "./value/arrays"
import {ArrayByStructureForTest}                from "./instance/ArrayByStructureForTest"
import {ArrayForTest}                           from "./instance/ArrayForTest"
import {IterableForTest}                        from "./instance/IterableForTest"
import {IterableWithCountForTest}               from "./instance/IterableWithCountForTest"
import {IterableWithLengthForTest}              from "./instance/IterableWithLengthForTest"
import {IterableWithLengthThatFailOnCount}      from "./instance/IterableWithLengthThatFailOnCount"
import {IterableWithNullPossibleSize}           from "./instance/IterableWithNullPossibleSize"
import {IterableWithSizeForTest}                from "./instance/IterableWithSizeForTest"
import {IterableWithSizeThatFailOnLength}       from "./instance/IterableWithSizeThatFailOnLength"
import {IteratorByStructureForTest}             from "./instance/IteratorByStructureForTest"
import {IteratorForTest}                        from "./instance/IteratorForTest"
import {SetByStructureForTest}                  from "./instance/SetByStructureForTest"
import {SetForTest}                             from "./instance/SetForTest"
import {CollectionIteratorFromArray}            from "./instance/CollectionIteratorFromArray"
import {CollectionIterator_ByStructure}         from "./instance/CollectionIterator_ByStructure"
import {CollectionHolderFromArray}              from "./instance/CollectionHolderFromArray"
import {CollectionHolder_ByStructure}           from "./instance/CollectionHolder_ByStructure"
import {MinimalistCollectionHolderFromArray}    from "./instance/MinimalistCollectionHolderFromArray"
import {MinimalistCollectionHolder_ByStructure} from "./instance/MinimalistCollectionHolder_ByStructure"

import {ArrayAsCollectionHolder}       from "../src/ArrayAsCollectionHolder"
import {ArrayOf1AsCollectionHolder}    from "../src/ArrayOf1AsCollectionHolder"
import {ArrayOf2AsCollectionHolder}    from "../src/ArrayOf2AsCollectionHolder"
import {CollectionHolderOf1}           from "../src/CollectionHolderOf1"
import {CollectionHolderOf2}           from "../src/CollectionHolderOf2"
import {GenericCollectionHolder}       from "../src/GenericCollectionHolder"
import {LazyCollectionHolder}          from "../src/LazyCollectionHolder"
import {LazyCollectionHolderOf0Or1}    from "../src/LazyCollectionHolderOf0Or1"
import {LazyCollectionHolderOf0Or1Or2} from "../src/LazyCollectionHolderOf0Or1Or2"
import {LazyCollectionHolderOf1}       from "../src/LazyCollectionHolderOf1"
import {LazyCollectionHolderOf1Or2}    from "../src/LazyCollectionHolderOf1Or2"
import {LazyCollectionHolderOf2}       from "../src/LazyCollectionHolderOf2"
import {SetAsCollectionHolder}         from "../src/SetAsCollectionHolder"
import {SetOf1AsCollectionHolder}      from "../src/SetOf1AsCollectionHolder"
import {SetOf2AsCollectionHolder}      from "../src/SetOf2AsCollectionHolder"
import {EmptyOptional}                 from "../src/optional/EmptyOptional"
import {Optional}                      from "../src/optional/Optional"
import {Couple}                        from "../src/tuple/Couple"

describe("CollectionHolderTest (constructor)", () => {

    describe("GenericCollectionHolder", () => {
        test("empty - array",                                                    () => expect(new GenericCollectionHolder(new ArrayForTest(EMPTY,),),)                            .toBeEmpty(),)
        test("empty - array (by structure)",                                     () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(EMPTY,),),)                 .toBeEmpty(),)
        test("empty - set",                                                      () => expect(new GenericCollectionHolder(new SetForTest(EMPTY,),),)                              .toBeEmpty(),)
        test("empty - set (by structure)",                                       () => expect(new GenericCollectionHolder(new SetByStructureForTest(EMPTY,),),)                   .toBeEmpty(),)
        test("empty - collection holder",                                        () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(EMPTY,),),)               .toBeEmpty(),)
        test("empty - collection holder (by structure)",                         () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(EMPTY,),),)            .toBeEmpty(),)
        test("empty - minimalist collection holder",                             () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(EMPTY,),),)     .toBeEmpty(),)
        test("empty - minimalist collection holder (by structure)",              () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(EMPTY,),),)  .toBeEmpty(),)
        test("empty - collection iterator",                                      () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(EMPTY,),),)             .toBeEmpty(),)
        test("empty - collection iterator (by structure)",                       () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(EMPTY,),),)          .toBeEmpty(),)
        test("empty - iterator",                                                 () => expect(new GenericCollectionHolder(new IteratorForTest(EMPTY,),),)                         .toBeEmpty(),)
        test("empty - iterator (by structure)",                                  () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(EMPTY,),),)              .toBeEmpty(),)
        test("empty - iterable",                                                 () => expect(new GenericCollectionHolder(new IterableForTest(EMPTY,),),)                         .toBeEmpty(),)
        test("empty - iterable with size",                                       () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(EMPTY,),),)                 .toBeEmpty(),)
        test("empty - iterable with length",                                     () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(EMPTY,),),)               .toBeEmpty(),)
        test("empty - iterable with count",                                      () => expect(new GenericCollectionHolder(new IterableWithCountForTest(EMPTY,),),)                .toBeEmpty(),)
        test("empty - iterable with possible size (all null)",                   () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(EMPTY,),),)            .toBeEmpty(),)
        test("empty - iterable with possible size (size + fail length)",         () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(EMPTY,),),)        .toBeEmpty(),)
        test("empty - iterable with possible size (length + fail count)",        () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(EMPTY,),),)       .toBeEmpty(),)
        test("1 field [0] - array",                                              () => expect(new GenericCollectionHolder(new ArrayForTest(A,),)[0],)                             .toBe('a',),)
        test("1 field [0] - array (by structure)",                               () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(A,),)[0],)                  .toBe('a',),)
        test("1 field [0] - set",                                                () => expect(new GenericCollectionHolder(new SetForTest(A,),)[0],)                               .toBe('a',),)
        test("1 field [0] - set (by structure)",                                 () => expect(new GenericCollectionHolder(new SetByStructureForTest(A,),)[0],)                    .toBe('a',),)
        test("1 field [0] - collection holder",                                  () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(A,),)[0],)                .toBe('a',),)
        test("1 field [0] - collection holder (by structure)",                   () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(A,),)[0],)             .toBe('a',),)
        test("1 field [0] - minimalist collection holder",                       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(A,),)[0],)      .toBe('a',),)
        test("1 field [0] - minimalist collection holder (by structure)",        () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(A,),)[0],)   .toBe('a',),)
        test("1 field [0] - collection iterator",                                () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(A,),)[0],)              .toBe('a',),)
        test("1 field [0] - collection iterator (by structure)",                 () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(A,),)[0],)           .toBe('a',),)
        test("1 field [0] - iterator",                                           () => expect(new GenericCollectionHolder(new IteratorForTest(A,),)[0],)                          .toBe('a',),)
        test("1 field [0] - iterator (by structure)",                            () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(A,),)[0],)               .toBe('a',),)
        test("1 field [0] - iterable",                                           () => expect(new GenericCollectionHolder(new IterableForTest(A,),)[0],)                          .toBe('a',),)
        test("1 field [0] - iterable with size",                                 () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(A,),)[0],)                  .toBe('a',),)
        test("1 field [0] - iterable with length",                               () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(A,),)[0],)                .toBe('a',),)
        test("1 field [0] - iterable with count",                                () => expect(new GenericCollectionHolder(new IterableWithCountForTest(A,),)[0],)                 .toBe('a',),)
        test("1 field [0] - iterable with possible size (all null)",             () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(A,),)[0],)             .toBe('a',),)
        test("1 field [0] - iterable with possible size (size + fail length)",   () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(A,),)[0],)         .toBe('a',),)
        test("1 field [0] - iterable with possible size (length + fail count)",  () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(A,),)[0],)        .toBe('a',),)
        test("2 fields [0] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(AB,),)[0],)                            .toBe('a',),)
        test("2 fields [0] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(AB,),)[0],)                 .toBe('a',),)
        test("2 fields [0] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(AB,),)[0],)                              .toBe('a',),)
        test("2 fields [0] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(AB,),)[0],)                   .toBe('a',),)
        test("2 fields [0] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(AB,),)[0],)               .toBe('a',),)
        test("2 fields [0] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(AB,),)[0],)            .toBe('a',),)
        test("2 fields [0] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(AB,),)[0],)     .toBe('a',),)
        test("2 fields [0] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(AB,),)[0],)  .toBe('a',),)
        test("2 fields [0] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(AB,),)[0],)             .toBe('a',),)
        test("2 fields [0] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(AB,),)[0],)          .toBe('a',),)
        test("2 fields [0] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(AB,),)[0],)                         .toBe('a',),)
        test("2 fields [0] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(AB,),)[0],)              .toBe('a',),)
        test("2 fields [0] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(AB,),)[0],)                         .toBe('a',),)
        test("2 fields [0] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(AB,),)[0],)                 .toBe('a',),)
        test("2 fields [0] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(AB,),)[0],)               .toBe('a',),)
        test("2 fields [0] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(AB,),)[0],)                .toBe('a',),)
        test("2 fields [0] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(AB,),)[0],)            .toBe('a',),)
        test("2 fields [0] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(AB,),)[0],)        .toBe('a',),)
        test("2 fields [0] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(AB,),)[0],)       .toBe('a',),)
        test("2 fields [1] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(AB,),)[1],)                            .toBe('b',),)
        test("2 fields [1] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(AB,),)[1],)                 .toBe('b',),)
        test("2 fields [1] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(AB,),)[1],)                              .toBe('b',),)
        test("2 fields [1] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(AB,),)[1],)                   .toBe('b',),)
        test("2 fields [1] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(AB,),)[1],)               .toBe('b',),)
        test("2 fields [1] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(AB,),)[1],)            .toBe('b',),)
        test("2 fields [1] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(AB,),)[1],)     .toBe('b',),)
        test("2 fields [1] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(AB,),)[1],)  .toBe('b',),)
        test("2 fields [1] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(AB,),)[1],)             .toBe('b',),)
        test("2 fields [1] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(AB,),)[1],)          .toBe('b',),)
        test("2 fields [1] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(AB,),)[1],)                         .toBe('b',),)
        test("2 fields [1] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(AB,),)[1],)              .toBe('b',),)
        test("2 fields [1] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(AB,),)[1],)                         .toBe('b',),)
        test("2 fields [1] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(AB,),)[1],)                 .toBe('b',),)
        test("2 fields [1] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(AB,),)[1],)               .toBe('b',),)
        test("2 fields [1] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(AB,),)[1],)                .toBe('b',),)
        test("2 fields [1] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(AB,),)[1],)            .toBe('b',),)
        test("2 fields [1] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(AB,),)[1],)        .toBe('b',),)
        test("2 fields [1] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(AB,),)[1],)       .toBe('b',),)
        test("3 fields [0] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABC,),)[0],)                           .toBe('a',),)
        test("3 fields [0] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABC,),)[0],)                .toBe('a',),)
        test("3 fields [0] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABC,),)[0],)                             .toBe('a',),)
        test("3 fields [0] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABC,),)[0],)                  .toBe('a',),)
        test("3 fields [0] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABC,),)[0],)              .toBe('a',),)
        test("3 fields [0] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABC,),)[0],)           .toBe('a',),)
        test("3 fields [0] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABC,),)[0],)    .toBe('a',),)
        test("3 fields [0] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABC,),)[0],) .toBe('a',),)
        test("3 fields [0] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABC,),)[0],)            .toBe('a',),)
        test("3 fields [0] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABC,),)[0],)         .toBe('a',),)
        test("3 fields [0] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABC,),)[0],)                        .toBe('a',),)
        test("3 fields [0] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABC,),)[0],)             .toBe('a',),)
        test("3 fields [0] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABC,),)[0],)                        .toBe('a',),)
        test("3 fields [0] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABC,),)[0],)                .toBe('a',),)
        test("3 fields [0] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABC,),)[0],)              .toBe('a',),)
        test("3 fields [0] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABC,),)[0],)               .toBe('a',),)
        test("3 fields [0] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABC,),)[0],)           .toBe('a',),)
        test("3 fields [0] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABC,),)[0],)       .toBe('a',),)
        test("3 fields [0] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABC,),)[0],)      .toBe('a',),)
        test("3 fields [1] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABC,),)[1],)                           .toBe('b',),)
        test("3 fields [1] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABC,),)[1],)                .toBe('b',),)
        test("3 fields [1] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABC,),)[1],)                             .toBe('b',),)
        test("3 fields [1] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABC,),)[1],)                  .toBe('b',),)
        test("3 fields [1] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABC,),)[1],)              .toBe('b',),)
        test("3 fields [1] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABC,),)[1],)           .toBe('b',),)
        test("3 fields [1] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABC,),)[1],)    .toBe('b',),)
        test("3 fields [1] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABC,),)[1],) .toBe('b',),)
        test("3 fields [1] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABC,),)[1],)            .toBe('b',),)
        test("3 fields [1] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABC,),)[1],)         .toBe('b',),)
        test("3 fields [1] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABC,),)[1],)                        .toBe('b',),)
        test("3 fields [1] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABC,),)[1],)             .toBe('b',),)
        test("3 fields [1] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABC,),)[1],)                        .toBe('b',),)
        test("3 fields [1] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABC,),)[1],)                .toBe('b',),)
        test("3 fields [1] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABC,),)[1],)              .toBe('b',),)
        test("3 fields [1] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABC,),)[1],)               .toBe('b',),)
        test("3 fields [1] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABC,),)[1],)           .toBe('b',),)
        test("3 fields [1] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABC,),)[1],)       .toBe('b',),)
        test("3 fields [1] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABC,),)[1],)      .toBe('b',),)
        test("3 fields [2] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABC,),)[2],)                           .toBe('c',),)
        test("3 fields [2] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABC,),)[2],)                .toBe('c',),)
        test("3 fields [2] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABC,),)[2],)                             .toBe('c',),)
        test("3 fields [2] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABC,),)[2],)                  .toBe('c',),)
        test("3 fields [2] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABC,),)[2],)              .toBe('c',),)
        test("3 fields [2] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABC,),)[2],)           .toBe('c',),)
        test("3 fields [2] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABC,),)[2],)    .toBe('c',),)
        test("3 fields [2] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABC,),)[2],) .toBe('c',),)
        test("3 fields [2] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABC,),)[2],)            .toBe('c',),)
        test("3 fields [2] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABC,),)[2],)         .toBe('c',),)
        test("3 fields [2] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABC,),)[2],)                        .toBe('c',),)
        test("3 fields [2] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABC,),)[2],)             .toBe('c',),)
        test("3 fields [2] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABC,),)[2],)                        .toBe('c',),)
        test("3 fields [2] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABC,),)[2],)                .toBe('c',),)
        test("3 fields [2] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABC,),)[2],)              .toBe('c',),)
        test("3 fields [2] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABC,),)[2],)               .toBe('c',),)
        test("3 fields [2] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABC,),)[2],)           .toBe('c',),)
        test("3 fields [2] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABC,),)[2],)       .toBe('c',),)
        test("3 fields [2] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABC,),)[2],)      .toBe('c',),)
        test("4 fields [0] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABCD,),)[0],)                          .toBe('a',),)
        test("4 fields [0] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABCD,),)[0],)               .toBe('a',),)
        test("4 fields [0] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABCD,),)[0],)                            .toBe('a',),)
        test("4 fields [0] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABCD,),)[0],)                 .toBe('a',),)
        test("4 fields [0] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABCD,),)[0],)             .toBe('a',),)
        test("4 fields [0] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[0],)          .toBe('a',),)
        test("4 fields [0] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[0],)   .toBe('a',),)
        test("4 fields [0] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[0],).toBe('a',),)
        test("4 fields [0] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[0],)           .toBe('a',),)
        test("4 fields [0] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[0],)        .toBe('a',),)
        test("4 fields [0] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABCD,),)[0],)                       .toBe('a',),)
        test("4 fields [0] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABCD,),)[0],)            .toBe('a',),)
        test("4 fields [0] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABCD,),)[0],)                       .toBe('a',),)
        test("4 fields [0] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABCD,),)[0],)               .toBe('a',),)
        test("4 fields [0] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABCD,),)[0],)             .toBe('a',),)
        test("4 fields [0] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABCD,),)[0],)              .toBe('a',),)
        test("4 fields [0] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[0],)          .toBe('a',),)
        test("4 fields [0] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[0],)      .toBe('a',),)
        test("4 fields [0] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[0],)     .toBe('a',),)
        test("4 fields [1] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABCD,),)[1],)                          .toBe('b',),)
        test("4 fields [1] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABCD,),)[1],)               .toBe('b',),)
        test("4 fields [1] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABCD,),)[1],)                            .toBe('b',),)
        test("4 fields [1] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABCD,),)[1],)                 .toBe('b',),)
        test("4 fields [1] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABCD,),)[1],)             .toBe('b',),)
        test("4 fields [1] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[1],)          .toBe('b',),)
        test("4 fields [1] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[1],)   .toBe('b',),)
        test("4 fields [1] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[1],).toBe('b',),)
        test("4 fields [1] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[1],)           .toBe('b',),)
        test("4 fields [1] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[1],)        .toBe('b',),)
        test("4 fields [1] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABCD,),)[1],)                       .toBe('b',),)
        test("4 fields [1] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABCD,),)[1],)            .toBe('b',),)
        test("4 fields [1] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABCD,),)[1],)                       .toBe('b',),)
        test("4 fields [1] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABCD,),)[1],)               .toBe('b',),)
        test("4 fields [1] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABCD,),)[1],)             .toBe('b',),)
        test("4 fields [1] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABCD,),)[1],)              .toBe('b',),)
        test("4 fields [1] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[1],)          .toBe('b',),)
        test("4 fields [1] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[1],)      .toBe('b',),)
        test("4 fields [1] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[1],)     .toBe('b',),)
        test("4 fields [2] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABCD,),)[2],)                          .toBe('c',),)
        test("4 fields [2] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABCD,),)[2],)               .toBe('c',),)
        test("4 fields [2] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABCD,),)[2],)                            .toBe('c',),)
        test("4 fields [2] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABCD,),)[2],)                 .toBe('c',),)
        test("4 fields [2] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABCD,),)[2],)             .toBe('c',),)
        test("4 fields [2] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[2],)          .toBe('c',),)
        test("4 fields [2] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[2],)   .toBe('c',),)
        test("4 fields [2] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[2],).toBe('c',),)
        test("4 fields [2] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[2],)           .toBe('c',),)
        test("4 fields [2] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[2],)        .toBe('c',),)
        test("4 fields [2] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABCD,),)[2],)                       .toBe('c',),)
        test("4 fields [2] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABCD,),)[2],)            .toBe('c',),)
        test("4 fields [2] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABCD,),)[2],)                       .toBe('c',),)
        test("4 fields [2] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABCD,),)[2],)               .toBe('c',),)
        test("4 fields [2] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABCD,),)[2],)             .toBe('c',),)
        test("4 fields [2] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABCD,),)[2],)              .toBe('c',),)
        test("4 fields [2] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[2],)          .toBe('c',),)
        test("4 fields [2] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[2],)      .toBe('c',),)
        test("4 fields [2] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[2],)     .toBe('c',),)
        test("4 fields [3] - array",                                             () => expect(new GenericCollectionHolder(new ArrayForTest(ABCD,),)[3],)                          .toBe('d',),)
        test("4 fields [3] - array (by structure)",                              () => expect(new GenericCollectionHolder(new ArrayByStructureForTest(ABCD,),)[3],)               .toBe('d',),)
        test("4 fields [3] - set",                                               () => expect(new GenericCollectionHolder(new SetForTest(ABCD,),)[3],)                            .toBe('d',),)
        test("4 fields [3] - set (by structure)",                                () => expect(new GenericCollectionHolder(new SetByStructureForTest(ABCD,),)[3],)                 .toBe('d',),)
        test("4 fields [3] - collection holder",                                 () => expect(new GenericCollectionHolder(new CollectionHolderFromArray(ABCD,),)[3],)             .toBe('d',),)
        test("4 fields [3] - collection holder (by structure)",                  () => expect(new GenericCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[3],)          .toBe('d',),)
        test("4 fields [3] - minimalist collection holder",                      () => expect(new GenericCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[3],)   .toBe('d',),)
        test("4 fields [3] - minimalist collection holder (by structure)",       () => expect(new GenericCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[3],).toBe('d',),)
        test("4 fields [3] - collection iterator",                               () => expect(new GenericCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[3],)           .toBe('d',),)
        test("4 fields [3] - collection iterator (by structure)",                () => expect(new GenericCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[3],)        .toBe('d',),)
        test("4 fields [3] - iterator",                                          () => expect(new GenericCollectionHolder(new IteratorForTest(ABCD,),)[3],)                       .toBe('d',),)
        test("4 fields [3] - iterator (by structure)",                           () => expect(new GenericCollectionHolder(new IteratorByStructureForTest(ABCD,),)[3],)            .toBe('d',),)
        test("4 fields [3] - iterable",                                          () => expect(new GenericCollectionHolder(new IterableForTest(ABCD,),)[3],)                       .toBe('d',),)
        test("4 fields [3] - iterable with size",                                () => expect(new GenericCollectionHolder(new IterableWithSizeForTest(ABCD,),)[3],)               .toBe('d',),)
        test("4 fields [3] - iterable with length",                              () => expect(new GenericCollectionHolder(new IterableWithLengthForTest(ABCD,),)[3],)             .toBe('d',),)
        test("4 fields [3] - iterable with count",                               () => expect(new GenericCollectionHolder(new IterableWithCountForTest(ABCD,),)[3],)              .toBe('d',),)
        test("4 fields [3] - iterable with possible size (all null)",            () => expect(new GenericCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[3],)          .toBe('d',),)
        test("4 fields [3] - iterable with possible size (size + fail length)",  () => expect(new GenericCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[3],)      .toBe('d',),)
        test("4 fields [3] - iterable with possible size (length + fail count)", () => expect(new GenericCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[3],)     .toBe('d',),)
    },)

    test("CollectionHolderOf1", () => expect(new CollectionHolderOf1('a',)[0],).toBe('a',),)
    describe("CollectionHolderOf2", () => {
        test("[0]", () => expect(new CollectionHolderOf2("a", "b",)[0],).toBe('a',),)
        test("[1]", () => expect(new CollectionHolderOf2("a", "b",)[1],).toBe('b',),)
    },)

    describe("ArrayAsCollectionHolder", () => {
        test("empty",        () => expect(new ArrayAsCollectionHolder(EMPTY,),)  .toBeEmpty(),)
        test("1 field [0]",  () => expect(new ArrayAsCollectionHolder(A,)[0],)   .toBe('a',),)
        test("2 fields [0]", () => expect(new ArrayAsCollectionHolder(AB,)[0],)  .toBe('a',),)
        test("2 fields [1]", () => expect(new ArrayAsCollectionHolder(AB,)[1],)  .toBe('b',),)
        test("3 fields [0]", () => expect(new ArrayAsCollectionHolder(ABC,)[0],) .toBe('a',),)
        test("3 fields [1]", () => expect(new ArrayAsCollectionHolder(ABC,)[1],) .toBe('b',),)
        test("3 fields [2]", () => expect(new ArrayAsCollectionHolder(ABC,)[2],) .toBe('c',),)
        test("4 fields [0]", () => expect(new ArrayAsCollectionHolder(ABCD,)[0],).toBe('a',),)
        test("4 fields [1]", () => expect(new ArrayAsCollectionHolder(ABCD,)[1],).toBe('b',),)
        test("4 fields [2]", () => expect(new ArrayAsCollectionHolder(ABCD,)[2],).toBe('c',),)
        test("4 fields [3]", () => expect(new ArrayAsCollectionHolder(ABCD,)[3],).toBe('d',),)
    },)
    describe("ArrayOf1AsCollectionHolder", () => {
        // @ts-expect-error
        test("empty",    () => expect(() => new ArrayOf1AsCollectionHolder(EMPTY,),).toThrow(TypeError,),)
        test("1 field",  () => expect(      new ArrayOf1AsCollectionHolder(A,)[0],) .toBe('a',),)
        // @ts-expect-error
        test("2 fields", () => expect(() => new ArrayOf1AsCollectionHolder(AB,),)   .toThrow(TypeError,),)
        // @ts-expect-error
        test("3 fields", () => expect(() => new ArrayOf1AsCollectionHolder(ABC,),)  .toThrow(TypeError,),)
        // @ts-expect-error
        test("4 fields", () => expect(() => new ArrayOf1AsCollectionHolder(ABCD,),) .toThrow(TypeError,),)
    },)
    describe("ArrayOf2AsCollectionHolder", () => {
        // @ts-expect-error
        test("empty",        () => expect(() => new ArrayOf2AsCollectionHolder(EMPTY,),).toThrow(TypeError,),)
        // @ts-expect-error
        test("1 field",      () => expect(() => new ArrayOf2AsCollectionHolder(A,),)    .toThrow(TypeError,),)
        test("2 fields [0]", () => expect(      new ArrayOf2AsCollectionHolder(AB,)[0],).toBe('a',),)
        test("2 fields [1]", () => expect(      new ArrayOf2AsCollectionHolder(AB,)[1],).toBe('b',),)
        // @ts-expect-error
        test("3 fields",     () => expect(() => new ArrayOf2AsCollectionHolder(ABC,),)  .toThrow(TypeError,),)
        // @ts-expect-error
        test("4 fields",     () => expect(() => new ArrayOf2AsCollectionHolder(ABCD,),) .toThrow(TypeError,),)
    },)

    describe("SetAsCollectionHolder", () => {
        // README: We use onEach to initialize the instance fields
        test("empty",        () => expect(new SetAsCollectionHolder(new Set(),),)                         .toBeEmpty(),)
        test("1 field [0]",  () => expect(new SetAsCollectionHolder(new Set(A,),).onEach(_ => {},)[0],)   .toBe('a',),)
        test("2 fields [0]", () => expect(new SetAsCollectionHolder(new Set(AB,),).onEach(_ => {},)[0],)  .toBe('a',),)
        test("2 fields [1]", () => expect(new SetAsCollectionHolder(new Set(AB,),).onEach(_ => {},)[1],)  .toBe('b',),)
        test("3 fields [0]", () => expect(new SetAsCollectionHolder(new Set(ABC,),).onEach(_ => {},)[0],) .toBe('a',),)
        test("3 fields [1]", () => expect(new SetAsCollectionHolder(new Set(ABC,),).onEach(_ => {},)[1],) .toBe('b',),)
        test("3 fields [2]", () => expect(new SetAsCollectionHolder(new Set(ABC,),).onEach(_ => {},)[2],) .toBe('c',),)
        test("4 fields [0]", () => expect(new SetAsCollectionHolder(new Set(ABCD,),).onEach(_ => {},)[0],).toBe('a',),)
        test("4 fields [1]", () => expect(new SetAsCollectionHolder(new Set(ABCD,),).onEach(_ => {},)[1],).toBe('b',),)
        test("4 fields [2]", () => expect(new SetAsCollectionHolder(new Set(ABCD,),).onEach(_ => {},)[2],).toBe('c',),)
        test("4 fields [3]", () => expect(new SetAsCollectionHolder(new Set(ABCD,),).onEach(_ => {},)[3],).toBe('d',),)
    },)
    describe("SetOf1AsCollectionHolder", () => {
        test("empty",    () => expect(() => new SetOf1AsCollectionHolder(new Set(),),)     .toThrow(TypeError,),)
        test("1 field",  () => expect(      new SetOf1AsCollectionHolder(new Set(A,),)[0],).toBe('a',),)
        test("2 fields", () => expect(() => new SetOf1AsCollectionHolder(new Set(AB,),),)  .toThrow(TypeError,),)
        test("3 fields", () => expect(() => new SetOf1AsCollectionHolder(new Set(ABC,),),) .toThrow(TypeError,),)
        test("4 fields", () => expect(() => new SetOf1AsCollectionHolder(new Set(ABCD,),),).toThrow(TypeError,),)
    },)
    describe("SetOf2AsCollectionHolder", () => {
        test("empty",        () => expect(() => new SetOf2AsCollectionHolder(new Set(),),)     .toThrow(TypeError,),)
        test("1 field",      () => expect(() => new SetOf2AsCollectionHolder(new Set(A,),),)   .toThrow(TypeError,),)
        test("2 fields [0]", () => expect(new SetOf2AsCollectionHolder(new Set(AB,),)[0],)     .toBe('a',),)
        test("2 fields [1]", () => expect(new SetOf2AsCollectionHolder(new Set(AB,),)[1],)     .toBe('b',),)
        test("3 fields",     () => expect(() => new SetOf2AsCollectionHolder(new Set(ABC,),),) .toThrow(TypeError,),)
        test("4 fields",     () => expect(() => new SetOf2AsCollectionHolder(new Set(ABCD,),),).toThrow(TypeError,),)
    },)

    describe.skip("LazyCollectionHolder", () => {
        test("empty - array",                                                    () => expect(new LazyCollectionHolder(new ArrayForTest(EMPTY,),),)                            .toBeEmpty(),)
        test("empty - array (by structure)",                                     () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(EMPTY,),),)                 .toBeEmpty(),)
        test("empty - set",                                                      () => expect(new LazyCollectionHolder(new SetForTest(EMPTY,),),)                              .toBeEmpty(),)
        test("empty - set (by structure)",                                       () => expect(new LazyCollectionHolder(new SetByStructureForTest(EMPTY,),),)                   .toBeEmpty(),)
        test("empty - collection holder",                                        () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(EMPTY,),),)               .toBeEmpty(),)
        test("empty - collection holder (by structure)",                         () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(EMPTY,),),)            .toBeEmpty(),)
        test("empty - minimalist collection holder",                             () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(EMPTY,),),)     .toBeEmpty(),)
        test("empty - minimalist collection holder (by structure)",              () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(EMPTY,),),)  .toBeEmpty(),)
        test("empty - collection iterator",                                      () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(EMPTY,),),)             .toBeEmpty(),)
        test("empty - collection iterator (by structure)",                       () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(EMPTY,),),)          .toBeEmpty(),)
        test("empty - iterator",                                                 () => expect(new LazyCollectionHolder(new IteratorForTest(EMPTY,),),)                         .toBeEmpty(),)
        test("empty - iterator (by structure)",                                  () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(EMPTY,),),)              .toBeEmpty(),)
        test("empty - iterable",                                                 () => expect(new LazyCollectionHolder(new IterableForTest(EMPTY,),),)                         .toBeEmpty(),)
        test("empty - iterable with size",                                       () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(EMPTY,),),)                 .toBeEmpty(),)
        test("empty - iterable with length",                                     () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(EMPTY,),),)               .toBeEmpty(),)
        test("empty - iterable with count",                                      () => expect(new LazyCollectionHolder(new IterableWithCountForTest(EMPTY,),),)                .toBeEmpty(),)
        test("empty - iterable with possible size (all null)",                   () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(EMPTY,),),)            .toBeEmpty(),)
        test("empty - iterable with possible size (size + fail length)",         () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(EMPTY,),),)        .toBeEmpty(),)
        test("empty - iterable with possible size (length + fail count)",        () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(EMPTY,),),)       .toBeEmpty(),)
        test("1 field [0] - array",                                              () => expect(new LazyCollectionHolder(new ArrayForTest(A,),)[0],)                             .toBe('a',),)
        test("1 field [0] - array (by structure)",                               () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(A,),)[0],)                  .toBe('a',),)
        test("1 field [0] - set",                                                () => expect(new LazyCollectionHolder(new SetForTest(A,),)[0],)                               .toBe('a',),)
        test("1 field [0] - set (by structure)",                                 () => expect(new LazyCollectionHolder(new SetByStructureForTest(A,),)[0],)                    .toBe('a',),)
        test("1 field [0] - collection holder",                                  () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(A,),)[0],)                .toBe('a',),)
        test("1 field [0] - collection holder (by structure)",                   () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(A,),)[0],)             .toBe('a',),)
        test("1 field [0] - minimalist collection holder",                       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(A,),)[0],)      .toBe('a',),)
        test("1 field [0] - minimalist collection holder (by structure)",        () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(A,),)[0],)   .toBe('a',),)
        test("1 field [0] - collection iterator",                                () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(A,),)[0],)              .toBe('a',),)
        test("1 field [0] - collection iterator (by structure)",                 () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(A,),)[0],)           .toBe('a',),)
        test("1 field [0] - iterator",                                           () => expect(new LazyCollectionHolder(new IteratorForTest(A,),)[0],)                          .toBe('a',),)
        test("1 field [0] - iterator (by structure)",                            () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(A,),)[0],)               .toBe('a',),)
        test("1 field [0] - iterable",                                           () => expect(new LazyCollectionHolder(new IterableForTest(A,),)[0],)                          .toBe('a',),)
        test("1 field [0] - iterable with size",                                 () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(A,),)[0],)                  .toBe('a',),)
        test("1 field [0] - iterable with length",                               () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(A,),)[0],)                .toBe('a',),)
        test("1 field [0] - iterable with count",                                () => expect(new LazyCollectionHolder(new IterableWithCountForTest(A,),)[0],)                 .toBe('a',),)
        test("1 field [0] - iterable with possible size (all null)",             () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(A,),)[0],)             .toBe('a',),)
        test("1 field [0] - iterable with possible size (size + fail length)",   () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(A,),)[0],)         .toBe('a',),)
        test("1 field [0] - iterable with possible size (length + fail count)",  () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(A,),)[0],)        .toBe('a',),)
        test("2 fields [0] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(AB,),)[0],)                            .toBe('a',),)
        test("2 fields [0] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(AB,),)[0],)                 .toBe('a',),)
        test("2 fields [0] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(AB,),)[0],)                              .toBe('a',),)
        test("2 fields [0] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(AB,),)[0],)                   .toBe('a',),)
        test("2 fields [0] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(AB,),)[0],)               .toBe('a',),)
        test("2 fields [0] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(AB,),)[0],)            .toBe('a',),)
        test("2 fields [0] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(AB,),)[0],)     .toBe('a',),)
        test("2 fields [0] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(AB,),)[0],)  .toBe('a',),)
        test("2 fields [0] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(AB,),)[0],)             .toBe('a',),)
        test("2 fields [0] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(AB,),)[0],)          .toBe('a',),)
        test("2 fields [0] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(AB,),)[0],)                         .toBe('a',),)
        test("2 fields [0] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(AB,),)[0],)              .toBe('a',),)
        test("2 fields [0] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(AB,),)[0],)                         .toBe('a',),)
        test("2 fields [0] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(AB,),)[0],)                 .toBe('a',),)
        test("2 fields [0] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(AB,),)[0],)               .toBe('a',),)
        test("2 fields [0] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(AB,),)[0],)                .toBe('a',),)
        test("2 fields [0] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(AB,),)[0],)            .toBe('a',),)
        test("2 fields [0] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(AB,),)[0],)        .toBe('a',),)
        test("2 fields [0] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(AB,),)[0],)       .toBe('a',),)
        test("2 fields [1] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(AB,),)[1],)                            .toBe('b',),)
        test("2 fields [1] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(AB,),)[1],)                 .toBe('b',),)
        test("2 fields [1] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(AB,),)[1],)                              .toBe('b',),)
        test("2 fields [1] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(AB,),)[1],)                   .toBe('b',),)
        test("2 fields [1] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(AB,),)[1],)               .toBe('b',),)
        test("2 fields [1] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(AB,),)[1],)            .toBe('b',),)
        test("2 fields [1] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(AB,),)[1],)     .toBe('b',),)
        test("2 fields [1] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(AB,),)[1],)  .toBe('b',),)
        test("2 fields [1] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(AB,),)[1],)             .toBe('b',),)
        test("2 fields [1] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(AB,),)[1],)          .toBe('b',),)
        test("2 fields [1] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(AB,),)[1],)                         .toBe('b',),)
        test("2 fields [1] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(AB,),)[1],)              .toBe('b',),)
        test("2 fields [1] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(AB,),)[1],)                         .toBe('b',),)
        test("2 fields [1] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(AB,),)[1],)                 .toBe('b',),)
        test("2 fields [1] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(AB,),)[1],)               .toBe('b',),)
        test("2 fields [1] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(AB,),)[1],)                .toBe('b',),)
        test("2 fields [1] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(AB,),)[1],)            .toBe('b',),)
        test("2 fields [1] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(AB,),)[1],)        .toBe('b',),)
        test("2 fields [1] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(AB,),)[1],)       .toBe('b',),)
        test("3 fields [0] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABC,),)[0],)                           .toBe('a',),)
        test("3 fields [0] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABC,),)[0],)                .toBe('a',),)
        test("3 fields [0] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABC,),)[0],)                             .toBe('a',),)
        test("3 fields [0] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABC,),)[0],)                  .toBe('a',),)
        test("3 fields [0] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABC,),)[0],)              .toBe('a',),)
        test("3 fields [0] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABC,),)[0],)           .toBe('a',),)
        test("3 fields [0] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABC,),)[0],)    .toBe('a',),)
        test("3 fields [0] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABC,),)[0],) .toBe('a',),)
        test("3 fields [0] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABC,),)[0],)            .toBe('a',),)
        test("3 fields [0] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABC,),)[0],)         .toBe('a',),)
        test("3 fields [0] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABC,),)[0],)                        .toBe('a',),)
        test("3 fields [0] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABC,),)[0],)             .toBe('a',),)
        test("3 fields [0] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABC,),)[0],)                        .toBe('a',),)
        test("3 fields [0] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABC,),)[0],)                .toBe('a',),)
        test("3 fields [0] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABC,),)[0],)              .toBe('a',),)
        test("3 fields [0] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABC,),)[0],)               .toBe('a',),)
        test("3 fields [0] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABC,),)[0],)           .toBe('a',),)
        test("3 fields [0] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABC,),)[0],)       .toBe('a',),)
        test("3 fields [0] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABC,),)[0],)      .toBe('a',),)
        test("3 fields [1] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABC,),)[1],)                           .toBe('b',),)
        test("3 fields [1] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABC,),)[1],)                .toBe('b',),)
        test("3 fields [1] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABC,),)[1],)                             .toBe('b',),)
        test("3 fields [1] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABC,),)[1],)                  .toBe('b',),)
        test("3 fields [1] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABC,),)[1],)              .toBe('b',),)
        test("3 fields [1] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABC,),)[1],)           .toBe('b',),)
        test("3 fields [1] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABC,),)[1],)    .toBe('b',),)
        test("3 fields [1] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABC,),)[1],) .toBe('b',),)
        test("3 fields [1] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABC,),)[1],)            .toBe('b',),)
        test("3 fields [1] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABC,),)[1],)         .toBe('b',),)
        test("3 fields [1] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABC,),)[1],)                        .toBe('b',),)
        test("3 fields [1] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABC,),)[1],)             .toBe('b',),)
        test("3 fields [1] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABC,),)[1],)                        .toBe('b',),)
        test("3 fields [1] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABC,),)[1],)                .toBe('b',),)
        test("3 fields [1] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABC,),)[1],)              .toBe('b',),)
        test("3 fields [1] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABC,),)[1],)               .toBe('b',),)
        test("3 fields [1] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABC,),)[1],)           .toBe('b',),)
        test("3 fields [1] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABC,),)[1],)       .toBe('b',),)
        test("3 fields [1] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABC,),)[1],)      .toBe('b',),)
        test("3 fields [2] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABC,),)[2],)                           .toBe('c',),)
        test("3 fields [2] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABC,),)[2],)                .toBe('c',),)
        test("3 fields [2] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABC,),)[2],)                             .toBe('c',),)
        test("3 fields [2] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABC,),)[2],)                  .toBe('c',),)
        test("3 fields [2] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABC,),)[2],)              .toBe('c',),)
        test("3 fields [2] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABC,),)[2],)           .toBe('c',),)
        test("3 fields [2] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABC,),)[2],)    .toBe('c',),)
        test("3 fields [2] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABC,),)[2],) .toBe('c',),)
        test("3 fields [2] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABC,),)[2],)            .toBe('c',),)
        test("3 fields [2] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABC,),)[2],)         .toBe('c',),)
        test("3 fields [2] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABC,),)[2],)                        .toBe('c',),)
        test("3 fields [2] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABC,),)[2],)             .toBe('c',),)
        test("3 fields [2] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABC,),)[2],)                        .toBe('c',),)
        test("3 fields [2] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABC,),)[2],)                .toBe('c',),)
        test("3 fields [2] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABC,),)[2],)              .toBe('c',),)
        test("3 fields [2] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABC,),)[2],)               .toBe('c',),)
        test("3 fields [2] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABC,),)[2],)           .toBe('c',),)
        test("3 fields [2] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABC,),)[2],)       .toBe('c',),)
        test("3 fields [2] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABC,),)[2],)      .toBe('c',),)
        test("4 fields [0] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABCD,),)[0],)                          .toBe('a',),)
        test("4 fields [0] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABCD,),)[0],)               .toBe('a',),)
        test("4 fields [0] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABCD,),)[0],)                            .toBe('a',),)
        test("4 fields [0] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABCD,),)[0],)                 .toBe('a',),)
        test("4 fields [0] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABCD,),)[0],)             .toBe('a',),)
        test("4 fields [0] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[0],)          .toBe('a',),)
        test("4 fields [0] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[0],)   .toBe('a',),)
        test("4 fields [0] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[0],).toBe('a',),)
        test("4 fields [0] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[0],)           .toBe('a',),)
        test("4 fields [0] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[0],)        .toBe('a',),)
        test("4 fields [0] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABCD,),)[0],)                       .toBe('a',),)
        test("4 fields [0] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABCD,),)[0],)            .toBe('a',),)
        test("4 fields [0] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABCD,),)[0],)                       .toBe('a',),)
        test("4 fields [0] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABCD,),)[0],)               .toBe('a',),)
        test("4 fields [0] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABCD,),)[0],)             .toBe('a',),)
        test("4 fields [0] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABCD,),)[0],)              .toBe('a',),)
        test("4 fields [0] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[0],)          .toBe('a',),)
        test("4 fields [0] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[0],)      .toBe('a',),)
        test("4 fields [0] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[0],)     .toBe('a',),)
        test("4 fields [1] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABCD,),)[1],)                          .toBe('b',),)
        test("4 fields [1] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABCD,),)[1],)               .toBe('b',),)
        test("4 fields [1] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABCD,),)[1],)                            .toBe('b',),)
        test("4 fields [1] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABCD,),)[1],)                 .toBe('b',),)
        test("4 fields [1] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABCD,),)[1],)             .toBe('b',),)
        test("4 fields [1] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[1],)          .toBe('b',),)
        test("4 fields [1] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[1],)   .toBe('b',),)
        test("4 fields [1] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[1],).toBe('b',),)
        test("4 fields [1] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[1],)           .toBe('b',),)
        test("4 fields [1] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[1],)        .toBe('b',),)
        test("4 fields [1] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABCD,),)[1],)                       .toBe('b',),)
        test("4 fields [1] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABCD,),)[1],)            .toBe('b',),)
        test("4 fields [1] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABCD,),)[1],)                       .toBe('b',),)
        test("4 fields [1] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABCD,),)[1],)               .toBe('b',),)
        test("4 fields [1] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABCD,),)[1],)             .toBe('b',),)
        test("4 fields [1] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABCD,),)[1],)              .toBe('b',),)
        test("4 fields [1] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[1],)          .toBe('b',),)
        test("4 fields [1] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[1],)      .toBe('b',),)
        test("4 fields [1] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[1],)     .toBe('b',),)
        test("4 fields [2] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABCD,),)[2],)                          .toBe('c',),)
        test("4 fields [2] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABCD,),)[2],)               .toBe('c',),)
        test("4 fields [2] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABCD,),)[2],)                            .toBe('c',),)
        test("4 fields [2] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABCD,),)[2],)                 .toBe('c',),)
        test("4 fields [2] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABCD,),)[2],)             .toBe('c',),)
        test("4 fields [2] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[2],)          .toBe('c',),)
        test("4 fields [2] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[2],)   .toBe('c',),)
        test("4 fields [2] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[2],).toBe('c',),)
        test("4 fields [2] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[2],)           .toBe('c',),)
        test("4 fields [2] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[2],)        .toBe('c',),)
        test("4 fields [2] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABCD,),)[2],)                       .toBe('c',),)
        test("4 fields [2] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABCD,),)[2],)            .toBe('c',),)
        test("4 fields [2] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABCD,),)[2],)                       .toBe('c',),)
        test("4 fields [2] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABCD,),)[2],)               .toBe('c',),)
        test("4 fields [2] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABCD,),)[2],)             .toBe('c',),)
        test("4 fields [2] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABCD,),)[2],)              .toBe('c',),)
        test("4 fields [2] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[2],)          .toBe('c',),)
        test("4 fields [2] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[2],)      .toBe('c',),)
        test("4 fields [2] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[2],)     .toBe('c',),)
        test("4 fields [3] - array",                                             () => expect(new LazyCollectionHolder(new ArrayForTest(ABCD,),)[3],)                          .toBe('d',),)
        test("4 fields [3] - array (by structure)",                              () => expect(new LazyCollectionHolder(new ArrayByStructureForTest(ABCD,),)[3],)               .toBe('d',),)
        test("4 fields [3] - set",                                               () => expect(new LazyCollectionHolder(new SetForTest(ABCD,),)[3],)                            .toBe('d',),)
        test("4 fields [3] - set (by structure)",                                () => expect(new LazyCollectionHolder(new SetByStructureForTest(ABCD,),)[3],)                 .toBe('d',),)
        test("4 fields [3] - collection holder",                                 () => expect(new LazyCollectionHolder(new CollectionHolderFromArray(ABCD,),)[3],)             .toBe('d',),)
        test("4 fields [3] - collection holder (by structure)",                  () => expect(new LazyCollectionHolder(new CollectionHolder_ByStructure(ABCD,),)[3],)          .toBe('d',),)
        test("4 fields [3] - minimalist collection holder",                      () => expect(new LazyCollectionHolder(new MinimalistCollectionHolderFromArray(ABCD,),)[3],)   .toBe('d',),)
        test("4 fields [3] - minimalist collection holder (by structure)",       () => expect(new LazyCollectionHolder(new MinimalistCollectionHolder_ByStructure(ABCD,),)[3],).toBe('d',),)
        test("4 fields [3] - collection iterator",                               () => expect(new LazyCollectionHolder(new CollectionIteratorFromArray(ABCD,),)[3],)           .toBe('d',),)
        test("4 fields [3] - collection iterator (by structure)",                () => expect(new LazyCollectionHolder(new CollectionIterator_ByStructure(ABCD,),)[3],)        .toBe('d',),)
        test("4 fields [3] - iterator",                                          () => expect(new LazyCollectionHolder(new IteratorForTest(ABCD,),)[3],)                       .toBe('d',),)
        test("4 fields [3] - iterator (by structure)",                           () => expect(new LazyCollectionHolder(new IteratorByStructureForTest(ABCD,),)[3],)            .toBe('d',),)
        test("4 fields [3] - iterable",                                          () => expect(new LazyCollectionHolder(new IterableForTest(ABCD,),)[3],)                       .toBe('d',),)
        test("4 fields [3] - iterable with size",                                () => expect(new LazyCollectionHolder(new IterableWithSizeForTest(ABCD,),)[3],)               .toBe('d',),)
        test("4 fields [3] - iterable with length",                              () => expect(new LazyCollectionHolder(new IterableWithLengthForTest(ABCD,),)[3],)             .toBe('d',),)
        test("4 fields [3] - iterable with count",                               () => expect(new LazyCollectionHolder(new IterableWithCountForTest(ABCD,),)[3],)              .toBe('d',),)
        test("4 fields [3] - iterable with possible size (all null)",            () => expect(new LazyCollectionHolder(new IterableWithNullPossibleSize(ABCD,),)[3],)          .toBe('d',),)
        test("4 fields [3] - iterable with possible size (size + fail length)",  () => expect(new LazyCollectionHolder(new IterableWithSizeThatFailOnLength(ABCD,),)[3],)      .toBe('d',),)
        test("4 fields [3] - iterable with possible size (length + fail count)", () => expect(new LazyCollectionHolder(new IterableWithLengthThatFailOnCount(ABCD,),)[3],)     .toBe('d',),)
    },)
    test("LazyCollectionHolderOf1", () => expect(new LazyCollectionHolderOf1(() => 'a',)[0],).toBe('a',),)
    describe("LazyCollectionHolderOf2", () => {
        test("[0]", () => expect(new LazyCollectionHolderOf2(() => new Couple("a", "b",),)[0],).toBe('a',),)
        test("[1]", () => expect(new LazyCollectionHolderOf2(() => new Couple("a", "b",),)[1],).toBe('b',),)
    },)
    describe("LazyCollectionHolderOf0Or1", () => {
        test('0', () => expect(() => new LazyCollectionHolderOf0Or1(() => EmptyOptional.get,)[0],) .toThrow(TypeError,),)
        test('1', () => expect(      new LazyCollectionHolderOf0Or1(() => new Optional('a',),)[0],).toBe('a',),)
    },)
    describe("LazyCollectionHolderOf0Or1Or2", () => {
        test("null [0]",                         () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => null,)[0],)                                                            .toThrow(TypeError,),)
        test("null [1]",                         () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => null,)[1],)                                                            .toThrow(TypeError,),)
        test("undefined [0]",                    () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => undefined,)[0],)                                                       .toThrow(TypeError,),)
        test("undefined [1]",                    () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => undefined,)[1],)                                                       .toThrow(TypeError,),)
        test("empty optional [0]",               () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => EmptyOptional.get,)[0],)                                               .toThrow(TypeError,),)
        test("empty optional [1]",               () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => EmptyOptional.get,)[1],)                                               .toThrow(TypeError,),)
        test("couple (only empty) [0]",          () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Couple(EmptyOptional.get, EmptyOptional.get,),)[0],)               .toThrow(TypeError,),)
        test("couple (only empty) [1]",          () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Couple(EmptyOptional.get, EmptyOptional.get,),)[1],)               .toThrow(TypeError,),)
        test("optional couple (only empty) [0]", () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(EmptyOptional.get, EmptyOptional.get,),),)[1],).toThrow(TypeError,),)
        test("optional couple (only empty) [1]", () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(EmptyOptional.get, EmptyOptional.get,),),)[1],).toThrow(TypeError,),)

        test("couple (1 before) [0]",          () => expect(      new LazyCollectionHolderOf0Or1Or2(() => new Couple(new Optional("a",), EmptyOptional.get,),)[0],)               .toBe("a",),)
        test("couple (1 before) [1]",          () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Couple(new Optional("a",), EmptyOptional.get,),)[1],)               .toThrow(TypeError,),)
        test("optional couple (1 before) [0]", () => expect(      new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(new Optional("a",), EmptyOptional.get,),),)[0],).toBe("a",),)
        test("optional couple (1 before) [1]", () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(new Optional("a",), EmptyOptional.get,),),)[1],).toThrow(TypeError,),)
        test("couple (1 after) [0]",           () => expect(      new LazyCollectionHolderOf0Or1Or2(() => new Couple(EmptyOptional.get, new Optional("a",),),)[0],)               .toBe("a",),)
        test("couple (1 after) [1]",           () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Couple(EmptyOptional.get, new Optional("a",),),)[1],)               .toThrow(TypeError,),)
        test("optional couple (1 after) [0]",  () => expect(      new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(EmptyOptional.get, new Optional("a",),),),)[0],).toBe("a",),)
        test("optional couple (1 after) [1]",  () => expect(() => new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(EmptyOptional.get, new Optional("a",),),),)[1],).toThrow(TypeError,),)

        test("couple (2) [0]",          () => expect(new LazyCollectionHolderOf0Or1Or2(() => new Couple(new Optional("a",), new Optional("b",),),)[0],)               .toBe("a",),)
        test("couple (2) [1]",          () => expect(new LazyCollectionHolderOf0Or1Or2(() => new Couple(new Optional("a",), new Optional("b",),),)[1],)               .toBe("b",),)
        test("optional couple (2) [0]", () => expect(new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(new Optional("a",), new Optional("b",),),),)[0],).toBe('a',),)
        test("optional couple (2) [1]", () => expect(new LazyCollectionHolderOf0Or1Or2(() => new Optional(new Couple(new Optional("a",), new Optional("b",),),),)[1],).toBe("b",),)
    },)
    describe("LazyCollectionHolderOf1Or2", () => {
        test("1 field [0]",  () => expect(      new LazyCollectionHolderOf1Or2(() => new Couple('a', EmptyOptional.get,),)[0],) .toBe('a',),)
        test("1 field [1]",  () => expect(() => new LazyCollectionHolderOf1Or2(() => new Couple('a', EmptyOptional.get,),)[1],) .toThrow(TypeError,),)
        test("2 fields [0]", () => expect(      new LazyCollectionHolderOf1Or2(() => new Couple("a", new Optional("b",),),)[0],).toBe('a',),)
        test("2 fields [1]", () => expect(      new LazyCollectionHolderOf1Or2(() => new Couple("a", new Optional("b",),),)[1],).toBe('b',),)
    },)

},)
