//··························································
// Copyright (c) 2023-2026. Jonathan Bédard ~ JóôòKiwi
//
// This project is free to use.
// All the right is reserved to the author of this project.
// My projects:
//  - https://github.com/joooKiwi/type
//  - https://github.com/joooKiwi/lazy
//  - https://github.com/joooKiwi/collection
//  - https://github.com/joooKiwi/enumeration
//··························································

import {callbackAsFail0}        from "./value/callbacks (fail)"
import {callbackToString0}      from "./value/callbacks (string)"
import {everyInfiniteInstances} from "./value/instances"

import {ForbiddenIndexException} from "../src/exception/ForbiddenIndexException"

describe("CollectionHolderTest (∞)", () => {
describe.each(everyInfiniteInstances,)("%s", ({value: {instance,},},) => {
    //README: A stack overflow exception is expected to be done (and it may take a while → ≈7-10 seconds)

    describe("fields after method call", () => {
        test("isEmpty[0]",             () => expect(new instance().execute(it => it.isEmpty,)[0],)            .toBe('a',),)
        test("isEmpty[1]",             () => expect(new instance().execute(it => it.isEmpty,)[1],)            .toBeUndefined(),)
        test("isNotEmpty[0]",          () => expect(new instance().execute(it => it.isNotEmpty,)[0],)         .toBe('a',),)
        test("isNotEmpty[1]",          () => expect(new instance().execute(it => it.isNotEmpty,)[1],)         .toBeUndefined(),)
        test("hasExactly1Element[0]",  () => expect(new instance().execute(it => it.hasExactly1Element,)[0],) .toBe('a',),)
        test("hasExactly1Element[1]",  () => expect(new instance().execute(it => it.hasExactly1Element,)[1],) .toBe('a',),)
        test("hasExactly1Element[2]",  () => expect(new instance().execute(it => it.hasExactly1Element,)[2],) .toBeUndefined(),)
        test("hasAtMost1Element[0]",   () => expect(new instance().execute(it => it.hasAtMost1Element,)[0],)  .toBe('a',),)
        test("hasAtMost1Element[1]",   () => expect(new instance().execute(it => it.hasAtMost1Element,)[1],)  .toBe('a',),)
        test("hasAtMost1Element[2]",   () => expect(new instance().execute(it => it.hasAtMost1Element,)[2],)  .toBe('a',),)
        test("hasAtMost1Element[3]",   () => expect(new instance().execute(it => it.hasAtMost1Element,)[3],)  .toBeUndefined(),)
        test("hasAtLeast2Elements[0]", () => expect(new instance().execute(it => it.hasAtLeast2Elements,)[0],).toBe('a',),)
        test("hasAtLeast2Elements[1]", () => expect(new instance().execute(it => it.hasAtLeast2Elements,)[1],).toBe('a',),)
        test("hasAtLeast2Elements[1]", () => expect(new instance().execute(it => it.hasAtLeast2Elements,)[2],).toBe('a',),)
        test("hasAtLeast2Elements[2]", () => expect(new instance().execute(it => it.hasAtLeast2Elements,)[3],).toBeUndefined(),)
        test("hasExactly2Elements[0]", () => expect(new instance().execute(it => it.hasExactly2Elements,)[0],).toBe('a',),)
        test("hasExactly2Elements[1]", () => expect(new instance().execute(it => it.hasExactly2Elements,)[1],).toBe('a',),)
        test("hasExactly2Elements[1]", () => expect(new instance().execute(it => it.hasExactly2Elements,)[2],).toBe('a',),)
        test("hasExactly2Elements[2]", () => expect(new instance().execute(it => it.hasExactly2Elements,)[3],).toBeUndefined(),)
        test("hasAtMost2Elements[0]",  () => expect(new instance().execute(it => it.hasAtMost2Elements,)[0],) .toBe('a',),)
        test("hasAtMost2Elements[1]",  () => expect(new instance().execute(it => it.hasAtMost2Elements,)[1],) .toBe('a',),)
        test("hasAtMost2Elements[1]",  () => expect(new instance().execute(it => it.hasAtMost2Elements,)[2],) .toBe('a',),)
        test("hasAtMost2Elements[2]",  () => expect(new instance().execute(it => it.hasAtMost2Elements,)[3],) .toBeUndefined(),)
        test("hasDuplicate[0]",        () => expect(new instance().execute(it => it.hasDuplicate,)[0],)       .toBe('a',),)
        test("hasDuplicate[1]",        () => expect(new instance().execute(it => it.hasDuplicate,)[1],)       .toBeUndefined(),)
        test("hasNoDuplicates[0]",     () => expect(new instance().execute(it => it.hasNoDuplicates,)[0],)    .toBe('a',),)
        test("hasNoDuplicates[1]",     () => expect(new instance().execute(it => it.hasNoDuplicates,)[1],)    .toBeUndefined(),)
    },)
    describe("after ‥", () => {
        describe("get(0)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.get(0,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.get(0,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.get(0,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.get(0,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.get(0,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.get(0,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.get(0,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.get(0,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.get(0,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.get(0,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.get(0,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.get(0,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.get(0,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.get(0,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.get(0,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.get(0,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.get(0,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.get(0,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("get(1)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.get(1,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.get(1,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.get(1,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.get(1,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.get(1,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.get(1,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.get(1,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.get(1,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.get(1,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.get(1,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.get(1,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.get(1,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.get(1,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.get(1,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.get(1,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.get(1,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.get(1,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.get(1,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("get(2)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.get(2,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.get(2,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.get(2,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.get(2,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.get(2,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.get(2,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.get(2,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.get(2,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.get(2,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.get(2,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.get(2,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.get(2,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.get(2,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.get(2,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.get(2,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.get(2,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.get(2,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.get(2,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("isEmpty", () => {
            test("is empty",                () => expect(new instance().execute(it => it.isEmpty,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.isEmpty,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.isEmpty,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.isEmpty,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.isEmpty,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.isEmpty,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.isEmpty,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.isEmpty,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.isEmpty,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.isEmpty,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.isEmpty,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.isEmpty,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.isEmpty,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.isEmpty,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.isEmpty,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.isEmpty,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.isEmpty,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.isEmpty,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("isNotEmpty", () => {
            test("is empty",                () => expect(new instance().execute(it => it.isNotEmpty,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.isNotEmpty,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.isNotEmpty,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.isNotEmpty,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.isNotEmpty,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.isNotEmpty,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.isNotEmpty,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.isNotEmpty,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.isNotEmpty,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.isNotEmpty,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.isNotEmpty,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.isNotEmpty,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.isNotEmpty,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.isNotEmpty,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.isNotEmpty,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.isNotEmpty,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.isNotEmpty,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.isNotEmpty,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasExactly1Element", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasExactly1Element,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasExactly1Element,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasExactly1Element,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasExactly1Element,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasExactly1Element,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasExactly1Element,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasExactly1Element,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasExactly1Element,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasExactly1Element,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasExactly1Element,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasExactly1Element,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasExactly1Element,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasExactly1Element,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasExactly1Element,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasExactly1Element,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasExactly1Element,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasExactly1Element,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasExactly1Element,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasAtMost1Element", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasAtMost1Element,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasAtMost1Element,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasAtMost1Element,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasAtMost1Element,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasAtMost1Element,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasAtMost1Element,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasAtMost1Element,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasAtMost1Element,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasAtMost1Element,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasAtMost1Element,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasAtMost1Element,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasAtMost1Element,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasAtMost1Element,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasAtMost1Element,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasAtMost1Element,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasAtMost1Element,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasAtMost1Element,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasAtMost1Element,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasAtLeast2Elements", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasAtLeast2Elements,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasAtLeast2Elements,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasAtLeast2Elements,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasAtLeast2Elements,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasAtLeast2Elements,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasAtLeast2Elements,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasExactly2Elements", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasExactly2Elements,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasExactly2Elements,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasExactly2Elements,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasExactly2Elements,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasExactly2Elements,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasExactly2Elements,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasExactly2Elements,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasExactly2Elements,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasExactly2Elements,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasExactly2Elements,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasExactly2Elements,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasExactly2Elements,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasExactly2Elements,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasExactly2Elements,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasExactly2Elements,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasExactly2Elements,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasExactly2Elements,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasExactly2Elements,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasAtMost2Elements", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasAtMost2Elements,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasAtMost2Elements,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasAtMost2Elements,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasAtMost2Elements,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasAtMost2Elements,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasAtMost2Elements,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasAtMost2Elements,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasAtMost2Elements,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasAtMost2Elements,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasAtMost2Elements,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasAtMost2Elements,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasAtMost2Elements,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getFirst()", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getFirst(),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getFirst(),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getFirst(),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getFirst(),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getFirst(),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getFirst(),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getFirst(),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getFirst(),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getFirst(),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getFirst(),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getFirst(),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getFirst(),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getFirst(),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getFirst(),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getFirst(),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getFirst(),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getFirst(),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getFirst(),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getOrElse(0)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getOrElse(0, callbackAsFail0,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getOrElse(1)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getOrElse(1, callbackAsFail0,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getOrElse(2)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getOrElse(2, callbackAsFail0,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getFirstOrElse()", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getFirstOrElse(callbackAsFail0,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getOrNull(0)", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getOrNull(0,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getOrNull(0,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getOrNull(0,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getOrNull(0,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getOrNull(0,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getOrNull(0,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getOrNull(0,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getOrNull(0,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getOrNull(0,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getOrNull(0,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getOrNull(0,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getOrNull(0,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getOrNull(0,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getOrNull(0,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getOrNull(0,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getOrNull(0,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getOrNull(0,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getOrNull(0,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getOrNull(1", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getOrNull(1,),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getOrNull(1,),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getOrNull(1,),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getOrNull(1,),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getOrNull(1,),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getOrNull(1,),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getOrNull(1,),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getOrNull(1,),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getOrNull(1,),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getOrNull(1,),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getOrNull(1,),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getOrNull(1,),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getOrNull(1,),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getOrNull(1,),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getOrNull(1,),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getOrNull(1,),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getOrNull(1,),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getOrNull(1,),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("getFirstOrNull()", () => {
            test("is empty",                () => expect(new instance().execute(it => it.getFirstOrNull(),).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.getFirstOrNull(),).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.getFirstOrNull(),).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.getFirstOrNull(),).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.getFirstOrNull(),).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.getFirstOrNull(),).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.getFirstOrNull(),).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.getFirstOrNull(),).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.getFirstOrNull(),).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.getFirstOrNull(),).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.getFirstOrNull(),).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.getFirstOrNull(),).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.getFirstOrNull(),).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.getFirstOrNull(),).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.getFirstOrNull(),).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.getFirstOrNull(),).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.getFirstOrNull(),).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.getFirstOrNull(),).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasDuplicate", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasDuplicate,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasDuplicate,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasDuplicate,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasDuplicate,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasDuplicate,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasDuplicate,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasDuplicate,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasDuplicate,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasDuplicate,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasDuplicate,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasDuplicate,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasDuplicate,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasDuplicate,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasDuplicate,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasDuplicate,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasDuplicate,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasDuplicate,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasDuplicate,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
        describe("hasNoDuplicates", () => {
            test("is empty",                () => expect(new instance().execute(it => it.hasNoDuplicates,).isEmpty,)                         .toBeFalse(),)
            test("is not empty",            () => expect(new instance().execute(it => it.hasNoDuplicates,).isNotEmpty,)                      .toBeTrue(),)
            test("has exactly 1 element",   () => expect(new instance().execute(it => it.hasNoDuplicates,).hasExactly1Element,)              .toBeFalse(),)
            test("has at most 1 element",   () => expect(new instance().execute(it => it.hasNoDuplicates,).hasAtMost1Element,)               .toBeFalse(),)
            test("has at least 2 elements", () => expect(new instance().execute(it => it.hasNoDuplicates,).hasAtLeast2Elements,)             .toBeTrue(),)
            test("has exactly 2 elements",  () => expect(new instance().execute(it => it.hasNoDuplicates,).hasExactly2Elements,)             .toBeFalse(),)
            test("has at most 2 elements",  () => expect(new instance().execute(it => it.hasNoDuplicates,).hasAtMost2Elements,)              .toBeFalse(),)
            test("get: 0",                  () => expect(new instance().execute(it => it.hasNoDuplicates,).get(0,),)                         .toBe('a',),)
            test("get: 1",                  () => expect(new instance().execute(it => it.hasNoDuplicates,).get(1,),)                         .toBe('a',),)
            test("getFirst",                () => expect(new instance().execute(it => it.hasNoDuplicates,).getFirst(),)                      .toBe('a',),)
            test("getOrElse: 0",            () => expect(new instance().execute(it => it.hasNoDuplicates,).getOrElse(0, callbackAsFail0,),)  .toBe('a',),)
            test("getOrElse: 1",            () => expect(new instance().execute(it => it.hasNoDuplicates,).getOrElse(1, callbackAsFail0,),)  .toBe('a',),)
            test("getFirstOrElse",          () => expect(new instance().execute(it => it.hasNoDuplicates,).getFirstOrElse(callbackAsFail0,),).toBe('a',),)
            test("getOrNull: 0",            () => expect(new instance().execute(it => it.hasNoDuplicates,).getOrNull(0,),)                   .toBe('a',),)
            test("getOrNull: 1",            () => expect(new instance().execute(it => it.hasNoDuplicates,).getOrNull(1,),)                   .toBe('a',),)
            test("getFirstOrNull",          () => expect(new instance().execute(it => it.hasNoDuplicates,).getFirstOrNull(),)                .toBe('a',),)
            test("has duplicate",           () => expect(new instance().execute(it => it.hasNoDuplicates,).hasDuplicate,)                    .toBeTrue(),)
            test("has no duplicates",       () => expect(new instance().execute(it => it.hasNoDuplicates,).hasNoDuplicates,)                 .toBeFalse(),)
        },)
    },)

    describe("size", () => {
        test.concurrent("size",               async () => expect(() => new instance().size,)                     .toThrow(RangeError,),)
        test(           "is empty",                 () => expect(      new instance().isEmpty,)            .toBeFalse(),)
        test(           "is not empty",             () => expect(      new instance().isNotEmpty,)         .toBeTrue(),)
        test(           "has exactly 1 element",    () => expect(      new instance().hasExactly1Element,) .toBeFalse(),)
        test(           "has at most 1 element",    () => expect(      new instance().hasAtMost1Element,)  .toBeFalse(),)
        test(           "has at least 2 elements",  () => expect(      new instance().hasAtLeast2Elements,).toBeTrue(),)
        test(           "has exactly 2 elements",   () => expect(      new instance().hasExactly2Elements,).toBeFalse(),)
        test(           "has at most 2 elements",   () => expect(      new instance().hasAtMost2Elements,) .toBeFalse(),)
    },)
    describe("get", () => {
        test(           "get: NaN",       () => expect(() => new instance().get(NaN,),)      .toThrow(ForbiddenIndexException,),)
        test(           "get: -∞",        () => expect(() => new instance().get(-Infinity,),).toThrow(ForbiddenIndexException,),)
        test.concurrent("get: -1",  async () => expect(() => new instance().get(-1,),)       .toThrow(RangeError,),)
        test(           "get: 0",         () => expect(      new instance().get(0,),)        .toBe('a',),)
        test(           "get: 1",         () => expect(      new instance().get(1,),)        .toBe('a',),)
        test(           "get: +∞",        () => expect(() => new instance().get(Infinity,),) .toThrow(ForbiddenIndexException,),)
    },)
    test("getFirst", () => expect(new instance().getFirst(),).toBe('a',),)
    describe("getOrElse", () => {
        test(           "getOrElse: NaN",       () => expect(      new instance().getOrElse(NaN, callbackToString0,),)      .toBe('E',),)
        test(           "getOrElse: -∞",        () => expect(      new instance().getOrElse(-Infinity, callbackToString0,),).toBe('E',),)
        test.concurrent("getOrElse: -1",  async () => expect(() => new instance().getOrElse(-1, callbackAsFail0,),)         .toThrow(RangeError,),)
        test(           "getOrElse: 0",         () => expect(      new instance().getOrElse(0, callbackAsFail0,),)          .toBe('a',),)
        test(           "getOrElse: 1",         () => expect(      new instance().getOrElse(1, callbackAsFail0,),)          .toBe('a',),)
        test(           "getOrElse: +∞",        () => expect(      new instance().getOrElse(Infinity, callbackToString0,),) .toBe('E',),)
    },)
    test("getFirstOrElse", () => expect(new instance().getFirstOrElse(callbackAsFail0,),).toBe('a',),)
    describe("getOrNull", () => {
        test(           "getOrNull: NaN",       () => expect(      new instance().getOrNull(NaN,),)      .toBeNull(),)
        test(           "getOrNull: -∞",        () => expect(      new instance().getOrNull(-Infinity,),).toBeNull(),)
        test.concurrent("getOrNull: -1",  async () => expect(() => new instance().getOrNull(-1,),)       .toThrow(RangeError,),)
        test(           "getOrNull: 0",         () => expect(      new instance().getOrNull(0,),)        .toBe('a',),)
        test(           "getOrNull: 1",         () => expect(      new instance().getOrNull(1,),)        .toBe('a',),)
        test(           "getOrNull: +∞",        () => expect(      new instance().getOrNull(Infinity,),) .toBeNull(),)
    },)
    test("getFirstOrNull", () => expect(new instance().getFirstOrNull(),).toBe('a',),)
    describe("has", () => {
        test.concurrent("has null",          async () => expect(() => new instance().hasNull,)        .toThrow(RangeError,),)
        test.concurrent("has no nulls",      async () => expect(() => new instance().hasNoNulls,)     .toThrow(RangeError,),)
        test(           "has duplicate",           () => expect(      new instance().hasDuplicate,)   .toBeTrue(),)
        test(           "has no duplicates",       () => expect(      new instance().hasNoDuplicates,).toBeFalse(),)
    },)

},)},)
