/*******************************************************************************
 Copyright (c) 2023-2024. Jonathan Bédard ~ JóôòKiwi

 This project is free to use.
 All the right is reserved to the author of this project.
 ******************************************************************************/

import {everyCollectionInstancesAndExtensionFunctionAsCollectionHolder}                                                                                                                                                                                                                                                                                                                             from "./value/instances"
import {EmptyCollectionHolderForTest}                                                                                                                                                                                                                                                                                                                                                               from "./instance/EmptyCollectionHolderForTest"
import {expectToBeInstance}                                                                                                                                                                                                                                                                                                                                                                         from "./expect/expectToBeInstance"
import {callbackAsFalse0, callbackAsFalse1, callbackAsFalse2, callbackAsTrue0, callbackAsTrue1, callbackAsTrue2, falseCallbacks, trueCallbacks}                                                                                                                                                                                                                                                     from "./value/callbacks (boolean)"
import {callbackAsFail0, callbackAsFail1, callbackAsFail2}                                                                                                                                                                                                                                                                                                                                          from "./value/callbacks (fail)"
import {callbackIsOver0, callbackIsOver0Alt, callbackIsOver1, callbackIsOver1Alt, callbackIsOver2, callbackIsOver2Alt, callbackIsOver3, callbackIsOver3Alt, callbackIsOver4, callbackIsOver4Alt, callbackIsUnder0, callbackIsUnder0Alt, callbackIsUnder1, callbackIsUnder1Alt, callbackIsUnder2, callbackIsUnder2Alt, callbackIsUnder3, callbackIsUnder3Alt, callbackIsUnder4, callbackIsUnder4Alt} from "./value/callbacks (number)"
import {callbackIsOverA, callbackIsOverAAlt, callbackIsOverB, callbackIsOverBAlt, callbackIsOverC, callbackIsOverCAlt, callbackIsOverD, callbackIsOverDAlt, callbackIsOverE, callbackIsOverEAlt, callbackIsUnderA, callbackIsUnderAAlt, callbackIsUnderB, callbackIsUnderBAlt, callbackIsUnderC, callbackIsUnderCAlt, callbackIsUnderD, callbackIsUnderDAlt, callbackIsUnderE, callbackIsUnderEAlt} from "./value/callbacks (string)"
import {A, AB, ABC, ABCD, B, BCD, CD, D, EMPTY}                                                                                                                                                                                                                                                                                                                                                     from "./value/arrays"

import {CollectionConstants}     from "../src/CollectionConstants"
import {ForbiddenIndexException} from "../src/exception/ForbiddenIndexException"

describe("CollectionHolderTest (take)", () => {

    describe("EmptyCollectionHolder", () => {
        test("take",                 () => expectToBeInstance(new EmptyCollectionHolderForTest(), it => it.take(),),)
        test("takeWhile",            () => expectToBeInstance(new EmptyCollectionHolderForTest(), it => it.takeWhile(),),)
        test("takeWhileIndexed",     () => expectToBeInstance(new EmptyCollectionHolderForTest(), it => it.takeWhileIndexed(),),)
        test("takeLast",             () => expectToBeInstance(new EmptyCollectionHolderForTest(), it => it.takeLast(),),)
        test("takeLastWhile",        () => expectToBeInstance(new EmptyCollectionHolderForTest(), it => it.takeLastWhile(),),)
        test("takeLastWhileIndexed", () => expectToBeInstance(new EmptyCollectionHolderForTest(), it => it.takeLastWhileIndexed(),),)
    },)

    describe.each(everyCollectionInstancesAndExtensionFunctionAsCollectionHolder,)("%s", ({value: {instance, isExtension,},},) => {
        if (!isExtension)
            describe("get() being called", () => {
                describe("take", () => {
                    describe("empty", () => {
                        test("NaN", () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.take(NaN,),).amountOfCall,).toBe(0,),)
                        test("-∞",  () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.take(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-1",  () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.take(-1,),).amountOfCall,).toBe(0,),)
                        test('0',   () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.take(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.take(1,),).amountOfCall,).toBe(0,),)
                        test("+∞",  () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.take(Infinity,),).amountOfCall,).toBe(0,),)
                    },)
                    describe("1 field", () => {
                        test("NaN", () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.executeWhileExpectingForbiddenException(it => it.take(NaN,),),).amountOfCall,).toBe(1,),)
                        test("-∞",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-2",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(-2,),).amountOfCall,).toBe(0,),)
                        test("-1",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(-1,),).amountOfCall,).toBe(0,),)
                        test('0',   () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(1,),).amountOfCall,).toBe(1,),)
                        test('2',   () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(2,),).amountOfCall,).toBe(1,),)
                        test("+∞",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.take(Infinity,),).amountOfCall,).toBe(1,),)
                    },)
                    describe("2 fields", () => {
                        test("NaN", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.executeWhileExpectingForbiddenException(it => it.take(NaN,),),).amountOfCall,).toBe(2,),)
                        test("-∞",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-3",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(-3,),).amountOfCall,).toBe(0,),)
                        test("-2",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(-2,),).amountOfCall,).toBe(0,),)
                        test("-1",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(-1,),).amountOfCall,).toBe(1,),)
                        test('0',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(1,),).amountOfCall,).toBe(1,),)
                        test('2',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(2,),).amountOfCall,).toBe(2,),)
                        test('3',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(3,),).amountOfCall,).toBe(2,),)
                        test("+∞",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.take(Infinity,),).amountOfCall,).toBe(2,),)
                    },)
                    describe("4 fields", () => {
                        test("NaN", () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.executeWhileExpectingForbiddenException(it => it.take(NaN,),),).amountOfCall,).toBe(4,),)
                        test("-∞",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-5",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(-5,),).amountOfCall,).toBe(0,),)
                        test("-4",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(-4,),).amountOfCall,).toBe(0,),)
                        test("-3",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(-3,),).amountOfCall,).toBe(1,),)
                        test("-2",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(-2,),).amountOfCall,).toBe(2,),)
                        test("-1",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(-1,),).amountOfCall,).toBe(3,),)
                        test('0',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(1,),).amountOfCall,).toBe(1,),)
                        test('2',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(2,),).amountOfCall,).toBe(2,),)
                        test('3',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(3,),).amountOfCall,).toBe(3,),)
                        test('4',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(4,),).amountOfCall,).toBe(4,),)
                        test('5',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(5,),).amountOfCall,).toBe(4,),)
                        test("+∞",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.take(Infinity,),).amountOfCall,).toBe(4,),)
                    },)
                },)
                describe("takeWhile", () => {
                    test("true: 0 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhile(callbackAsTrue0,),).amountOfCall,).toBe(2,),)
                    test("true: 1 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhile(callbackAsTrue1,),).amountOfCall,).toBe(2,),)
                    test("true: 2 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhile(callbackAsTrue2,),).amountOfCall,).toBe(2,),)
                    test("false: 0 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhile(callbackAsFalse0,),).amountOfCall,).toBe(0,),)
                    test("false: 1 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhile(callbackAsFalse1,),).amountOfCall,).toBe(1,),)
                    test("false: 2 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhile(callbackAsFalse2,),).amountOfCall,).toBe(1,),)
                },)
                describe("takeWhileIndexed", () => {
                    test("true: 0 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhileIndexed(callbackAsTrue0,),).amountOfCall,).toBe(2,),)
                    test("true: 1 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhileIndexed(callbackAsTrue1,),).amountOfCall,).toBe(2,),)
                    test("true: 2 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhileIndexed(callbackAsTrue2,),).amountOfCall,).toBe(2,),)
                    test("false: 0 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhileIndexed(callbackAsFalse0,),).amountOfCall,).toBe(0,),)
                    test("false: 1 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhileIndexed(callbackAsFalse1,),).amountOfCall,).toBe(0,),)
                    test("false: 2 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeWhileIndexed(callbackAsFalse2,),).amountOfCall,).toBe(1,),)
                },)

                describe("takeLast", () => {
                    describe("empty", () => {
                        test("NaN", () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.takeLast(NaN,),).amountOfCall,).toBe(0,),)
                        test("-∞",  () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.takeLast(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-1",  () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.takeLast(-1,),).amountOfCall,).toBe(0,),)
                        test('0',   () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.takeLast(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.takeLast(1,),).amountOfCall,).toBe(0,),)
                        test("+∞",  () => expect(new instance(EMPTY,).executeWhileHavingIndexesOnField(it => it.takeLast(Infinity,),).amountOfCall,).toBe(0,),)
                    },)
                    describe("1 field", () => {
                        test("NaN", () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.executeWhileExpectingForbiddenException(it => it.takeLast(NaN,),),).amountOfCall,).toBe(1,),)
                        test("-∞",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-2",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(-2,),).amountOfCall,).toBe(0,),)
                        test("-1",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(-1,),).amountOfCall,).toBe(0,),)
                        test('0',   () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(1,),).amountOfCall,).toBe(1,),)
                        test('2',   () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(2,),).amountOfCall,).toBe(1,),)
                        test("+∞",  () => expect(new instance(A,).executeWhileHavingIndexesOnField(it => it.takeLast(Infinity,),).amountOfCall,).toBe(1,),)
                    },)
                    describe("2 fields", () => {
                        test("NaN", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.executeWhileExpectingForbiddenException(it => it.takeLast(NaN,),),).amountOfCall,).toBe(2,),)
                        test("-∞",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-3",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(-3,),).amountOfCall,).toBe(0,),)
                        test("-2",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(-2,),).amountOfCall,).toBe(0,),)
                        test("-1",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(-1,),).amountOfCall,).toBe(1,),)
                        test('0',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(1,),).amountOfCall,).toBe(1,),)
                        test('2',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(2,),).amountOfCall,).toBe(2,),)
                        test('3',   () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(3,),).amountOfCall,).toBe(2,),)
                        test("+∞",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLast(Infinity,),).amountOfCall,).toBe(2,),)
                    },)
                    describe("4 fields", () => {
                        test("NaN", () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.executeWhileExpectingForbiddenException(it => it.takeLast(NaN,),),).amountOfCall,).toBe(4,),)
                        test("-∞",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(-Infinity,),).amountOfCall,).toBe(0,),)
                        test("-5",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(-5,),).amountOfCall,).toBe(0,),)
                        test("-4",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(-4,),).amountOfCall,).toBe(0,),)
                        test("-3",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(-3,),).amountOfCall,).toBe(1,),)
                        test("-2",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(-2,),).amountOfCall,).toBe(2,),)
                        test("-1",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(-1,),).amountOfCall,).toBe(3,),)
                        test('0',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(0,),).amountOfCall,).toBe(0,),)
                        test('1',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(1,),).amountOfCall,).toBe(1,),)
                        test('2',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(2,),).amountOfCall,).toBe(2,),)
                        test('3',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(3,),).amountOfCall,).toBe(3,),)
                        test('4',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(4,),).amountOfCall,).toBe(4,),)
                        test('5',   () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(5,),).amountOfCall,).toBe(4,),)
                        test("+∞",  () => expect(new instance(ABCD,).executeWhileHavingIndexesOnField(it => it.takeLast(Infinity,),).amountOfCall,).toBe(4,),)
                    },)
                },)
                describe("takeLastWhile", () => {
                    test("true: 0 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhile(callbackAsTrue0,),).amountOfCall,).toBe(2,),)
                    test("true: 1 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhile(callbackAsTrue1,),).amountOfCall,).toBe(2,),)
                    test("true: 2 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhile(callbackAsTrue2,),).amountOfCall,).toBe(2,),)
                    test("false: 0 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhile(callbackAsFalse0,),).amountOfCall,).toBe(0,),)
                    test("false: 1 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhile(callbackAsFalse1,),).amountOfCall,).toBe(1,),)
                    test("false: 2 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhile(callbackAsFalse2,),).amountOfCall,).toBe(1,),)
                },)
                describe("takeLastWhileIndexed", () => {
                    test("true: 0 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhileIndexed(callbackAsTrue0,),).amountOfCall,).toBe(2,),)
                    test("true: 1 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhileIndexed(callbackAsTrue1,),).amountOfCall,).toBe(2,),)
                    test("true: 2 arguments",  () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhileIndexed(callbackAsTrue2,),).amountOfCall,).toBe(2,),)
                    test("false: 0 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhileIndexed(callbackAsFalse0,),).amountOfCall,).toBe(0,),)
                    test("false: 1 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhileIndexed(callbackAsFalse1,),).amountOfCall,).toBe(0,),)
                    test("false: 2 arguments", () => expect(new instance(AB,).executeWhileHavingIndexesOnField(it => it.takeLastWhileIndexed(callbackAsFalse2,),).amountOfCall,).toBe(1,),)
                },)
            },)

        describe("take", () => {
            describe("empty", () => {
                test("NaN", () => expect(new instance(EMPTY,).take(NaN,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-∞",  () => expect(new instance(EMPTY,).take(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-1",  () => expect(new instance(EMPTY,).take(-1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('0',   () => expect(new instance(EMPTY,).take(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(EMPTY,).take(1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("+∞",  () => expect(new instance(EMPTY,).take(Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
            },)
            describe("1 field", () => {
                test("NaN", () => expect(() => new instance(A,).take(NaN,),).toThrow(ForbiddenIndexException,),)
                test("-∞",  () => expect(new instance(A,).take(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-2",  () => expect(new instance(A,).take(-2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-1",  () => expect(new instance(A,).take(-1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('0',   () => expect(new instance(A,).take(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(A,).take(1,).toArray(),).toEqual(A,),)
                test('2',   () => expect(new instance(A,).take(2,).toArray(),).toEqual(A,),)
                test("+∞",  () => expect(new instance(A,).take(Infinity,).toArray(),).toEqual(A,),)
            },)
            describe("2 fields", () => {
                test("NaN", () => expect(() => new instance(AB,).take(NaN,),).toThrow(ForbiddenIndexException,),)
                test("-∞",  () => expect(new instance(AB,).take(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-3",  () => expect(new instance(AB,).take(-3,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-2",  () => expect(new instance(AB,).take(-2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-1",  () => expect(new instance(AB,).take(-1,).toArray(),).toEqual(A,),)
                test('0',   () => expect(new instance(AB,).take(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(AB,).take(1,).toArray(),).toEqual(A,),)
                test('2',   () => expect(new instance(AB,).take(2,).toArray(),).toEqual(AB,),)
                test('3',   () => expect(new instance(AB,).take(3,).toArray(),).toEqual(AB,),)
                test("+∞",  () => expect(new instance(AB,).take(Infinity,).toArray(),).toEqual(AB,),)
            },)
            describe("4 fields", () => {
                test("NaN", () => expect(() => new instance(ABCD,).take(NaN,),).toThrow(ForbiddenIndexException,),)
                test("-∞",  () => expect(new instance(ABCD,).take(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-5",  () => expect(new instance(ABCD,).take(-5,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-4",  () => expect(new instance(ABCD,).take(-4,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-3",  () => expect(new instance(ABCD,).take(-3,).toArray(),).toEqual(A,),)
                test("-2",  () => expect(new instance(ABCD,).take(-2,).toArray(),).toEqual(AB,),)
                test("-1",  () => expect(new instance(ABCD,).take(-1,).toArray(),).toEqual(ABC,),)
                test('0',   () => expect(new instance(ABCD,).take(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(ABCD,).take(1,).toArray(),).toEqual(A,),)
                test('2',   () => expect(new instance(ABCD,).take(2,).toArray(),).toEqual(AB,),)
                test('3',   () => expect(new instance(ABCD,).take(3,).toArray(),).toEqual(ABC,),)
                test('4',   () => expect(new instance(ABCD,).take(4,).toArray(),).toEqual(ABCD,),)
                test('5',   () => expect(new instance(ABCD,).take(5,).toArray(),).toEqual(ABCD,),)
                test("+∞",  () => expect(new instance(ABCD,).take(Infinity,).toArray(),).toEqual(ABCD,),)
            },)
        },)
        describe("takeWhile", () => {
            describe("empty", () => {
                test("0 arguments", () => expect(new instance(EMPTY,).takeWhile(callbackAsFail0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("1 argument",  () => expect(new instance(EMPTY,).takeWhile(callbackAsFail1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("2 arguments", () => expect(new instance(EMPTY,).takeWhile(callbackAsFail2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
            },)
            describe("boolean callbacks", () => {
                describe.each(trueCallbacks,)("true: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeWhile(it,).toArray(),).toEqual(A,),)
                    test("2 fields", () => expect(new instance(AB,).takeWhile(it,).toArray(),).toEqual(AB,),)
                    test("4 fields", () => expect(new instance(ABCD,).takeWhile(it,).toArray(),).toEqual(ABCD,),)
                },)
                describe.each(falseCallbacks,)("true: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeWhile(it,),).toBeEmpty(),)
                    test("2 fields", () => expect(new instance(AB,).takeWhile(it,),).toBeEmpty(),)
                    test("4 fields", () => expect(new instance(ABCD,).takeWhile(it,),).toBeEmpty(),)
                },)
            },)
            describe("1 field", () => {
                test('a', () => expect(new instance(A,).takeWhile(callbackIsUnderA,),).toBeEmpty(),)
                test('e', () => expect(new instance(A,).takeWhile(callbackIsUnderE,).toArray(),).toEqual(A,),)
                test('0', () => expect(new instance(A,).takeWhile(callbackIsUnder0Alt,),).toBeEmpty(),)
                test('4', () => expect(new instance(A,).takeWhile(callbackIsUnder4Alt,).toArray(),).toEqual(A,),)
            },)
            describe("2 fields", () => {
                test('a', () => expect(new instance(AB,).takeWhile(callbackIsUnderA,),).toBeEmpty(),)
                test('b', () => expect(new instance(AB,).takeWhile(callbackIsUnderB,).toArray(),).toEqual(A,),)
                test('e', () => expect(new instance(AB,).takeWhile(callbackIsUnderE,).toArray(),).toEqual(AB,),)
                test('0', () => expect(new instance(AB,).takeWhile(callbackIsUnder0Alt,),).toBeEmpty(),)
                test('1', () => expect(new instance(AB,).takeWhile(callbackIsUnder1Alt,).toArray(),).toEqual(A,),)
                test('4', () => expect(new instance(AB,).takeWhile(callbackIsUnder4Alt,).toArray(),).toEqual(AB,),)
            },)
            describe("4 fields", () => {
                test('a', () => expect(new instance(ABCD,).takeWhile(callbackIsUnderA,),).toBeEmpty(),)
                test('b', () => expect(new instance(ABCD,).takeWhile(callbackIsUnderB,).toArray(),).toEqual(A,),)
                test('c', () => expect(new instance(ABCD,).takeWhile(callbackIsUnderC,).toArray(),).toEqual(AB,),)
                test('d', () => expect(new instance(ABCD,).takeWhile(callbackIsUnderD,).toArray(),).toEqual(ABC,),)
                test('e', () => expect(new instance(ABCD,).takeWhile(callbackIsUnderE,).toArray(),).toEqual(ABCD,),)
                test('0', () => expect(new instance(ABCD,).takeWhile(callbackIsUnder0Alt,),).toBeEmpty(),)
                test('1', () => expect(new instance(ABCD,).takeWhile(callbackIsUnder1Alt,).toArray(),).toEqual(A,),)
                test('2', () => expect(new instance(ABCD,).takeWhile(callbackIsUnder2Alt,).toArray(),).toEqual(AB,),)
                test('3', () => expect(new instance(ABCD,).takeWhile(callbackIsUnder3Alt,).toArray(),).toEqual(ABC,),)
                test('4', () => expect(new instance(ABCD,).takeWhile(callbackIsUnder4Alt,).toArray(),).toEqual(ABCD,),)
            },)
        },)
        describe("takeWhileIndexed", () => {
            describe("empty", () => {
                test("0 arguments", () => expect(new instance(EMPTY,).takeWhileIndexed(callbackAsFail0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("1 argument",  () => expect(new instance(EMPTY,).takeWhileIndexed(callbackAsFail1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("2 arguments", () => expect(new instance(EMPTY,).takeWhileIndexed(callbackAsFail2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
            },)
            describe("boolean callbacks", () => {
                describe.each(trueCallbacks,)("true: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeWhileIndexed(it,).toArray(),).toEqual(A,),)
                    test("2 fields", () => expect(new instance(AB,).takeWhileIndexed(it,).toArray(),).toEqual(AB,),)
                    test("4 fields", () => expect(new instance(ABCD,).takeWhileIndexed(it,).toArray(),).toEqual(ABCD,),)
                },)
                describe.each(falseCallbacks,)("true: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeWhileIndexed(it,).toArray(),).toEqual(EMPTY,),)
                    test("2 fields", () => expect(new instance(AB,).takeWhileIndexed(it,).toArray(),).toEqual(EMPTY,),)
                    test("4 fields", () => expect(new instance(ABCD,).takeWhileIndexed(it,).toArray(),).toEqual(EMPTY,),)
                },)
            },)
            describe("1 field", () => {
                test('a', () => expect(new instance(A,).takeWhileIndexed(callbackIsUnderAAlt,),).toBeEmpty(),)
                test('e', () => expect(new instance(A,).takeWhileIndexed(callbackIsUnderEAlt,).toArray(),).toEqual(A,),)
                test('0', () => expect(new instance(A,).takeWhileIndexed(callbackIsUnder0,),).toBeEmpty(),)
                test('4', () => expect(new instance(A,).takeWhileIndexed(callbackIsUnder4,).toArray(),).toEqual(A,),)
            },)
            describe("2 fields", () => {
                test('a', () => expect(new instance(AB,).takeWhileIndexed(callbackIsUnderAAlt,),).toBeEmpty(),)
                test('b', () => expect(new instance(AB,).takeWhileIndexed(callbackIsUnderBAlt,).toArray(),).toEqual(A,),)
                test('e', () => expect(new instance(AB,).takeWhileIndexed(callbackIsUnderEAlt,).toArray(),).toEqual(AB,),)
                test('0', () => expect(new instance(AB,).takeWhileIndexed(callbackIsUnder0,),).toBeEmpty(),)
                test('1', () => expect(new instance(AB,).takeWhileIndexed(callbackIsUnder1,).toArray(),).toEqual(A,),)
                test('4', () => expect(new instance(AB,).takeWhileIndexed(callbackIsUnder4,).toArray(),).toEqual(AB,),)
            },)
            describe("4 fields", () => {
                test('a', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnderAAlt,),).toBeEmpty(),)
                test('b', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnderBAlt,).toArray(),).toEqual(A,),)
                test('c', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnderCAlt,).toArray(),).toEqual(AB,),)
                test('d', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnderDAlt,).toArray(),).toEqual(ABC,),)
                test('e', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnderEAlt,).toArray(),).toEqual(ABCD,),)
                test('0', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnder0,),).toBeEmpty(),)
                test('1', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnder1,).toArray(),).toEqual(A,),)
                test('2', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnder2,).toArray(),).toEqual(AB,),)
                test('3', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnder3,).toArray(),).toEqual(ABC,),)
                test('4', () => expect(new instance(ABCD,).takeWhileIndexed(callbackIsUnder4,).toArray(),).toEqual(ABCD,),)
            },)
        },)

        describe("takeLast", () => {
            describe("empty", () => {
                test("NaN", () => expect(new instance(EMPTY,).takeLast(NaN,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-∞",  () => expect(new instance(EMPTY,).takeLast(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-1",  () => expect(new instance(EMPTY,).takeLast(-1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('0',   () => expect(new instance(EMPTY,).takeLast(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(EMPTY,).takeLast(1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("+∞",  () => expect(new instance(EMPTY,).takeLast(Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
            },)
            describe("1 field", () => {
                test("NaN", () => expect(() => new instance(A,).takeLast(NaN,),).toThrow(ForbiddenIndexException,),)
                test("-∞",  () => expect(new instance(A,).takeLast(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-2",  () => expect(new instance(A,).takeLast(-2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-1",  () => expect(new instance(A,).takeLast(-1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('0',   () => expect(new instance(A,).takeLast(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(A,).takeLast(1,).toArray(),).toEqual(A,),)
                test('2',   () => expect(new instance(A,).takeLast(2,).toArray(),).toEqual(A,),)
                test("+∞",  () => expect(new instance(A,).takeLast(Infinity,).toArray(),).toEqual(A,),)
            },)
            describe("2 fields", () => {
                test("NaN", () => expect(() => new instance(AB,).takeLast(NaN,),).toThrow(ForbiddenIndexException,),)
                test("-∞",  () => expect(new instance(AB,).takeLast(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-3",  () => expect(new instance(AB,).takeLast(-3,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-2",  () => expect(new instance(AB,).takeLast(-2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-1",  () => expect(new instance(AB,).takeLast(-1,).toArray(),).toEqual(B,),)
                test('0',   () => expect(new instance(AB,).takeLast(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(AB,).takeLast(1,).toArray(),).toEqual(B,),)
                test('2',   () => expect(new instance(AB,).takeLast(2,).toArray(),).toEqual(AB,),)
                test('3',   () => expect(new instance(AB,).takeLast(3,).toArray(),).toEqual(AB,),)
                test("+∞",  () => expect(new instance(AB,).takeLast(Infinity,).toArray(),).toEqual(AB,),)
            },)
            describe("4 fields", () => {
                test("NaN", () => expect(() => new instance(ABCD,).takeLast(NaN,),).toThrow(ForbiddenIndexException,),)
                test("-∞",  () => expect(new instance(ABCD,).takeLast(-Infinity,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-5",  () => expect(new instance(ABCD,).takeLast(-5,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-4",  () => expect(new instance(ABCD,).takeLast(-4,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("-3",  () => expect(new instance(ABCD,).takeLast(-3,).toArray(),).toEqual(D,),)
                test("-2",  () => expect(new instance(ABCD,).takeLast(-2,).toArray(),).toEqual(CD,),)
                test("-1",  () => expect(new instance(ABCD,).takeLast(-1,).toArray(),).toEqual(BCD,),)
                test('0',   () => expect(new instance(ABCD,).takeLast(0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test('1',   () => expect(new instance(ABCD,).takeLast(1,).toArray(),).toEqual(D,),)
                test('2',   () => expect(new instance(ABCD,).takeLast(2,).toArray(),).toEqual(CD,),)
                test('3',   () => expect(new instance(ABCD,).takeLast(3,).toArray(),).toEqual(BCD,),)
                test('4',   () => expect(new instance(ABCD,).takeLast(4,).toArray(),).toEqual(ABCD,),)
                test('5',   () => expect(new instance(ABCD,).takeLast(5,).toArray(),).toEqual(ABCD,),)
                test("+∞",  () => expect(new instance(ABCD,).takeLast(Infinity,).toArray(),).toEqual(ABCD,),)
            },)
        },)
        describe("takeLastWhile", () => {
            describe("empty", () => {
                test("0 arguments", () => expect(new instance(EMPTY,).takeLastWhile(callbackAsFail0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("1 argument",  () => expect(new instance(EMPTY,).takeLastWhile(callbackAsFail1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("2 arguments", () => expect(new instance(EMPTY,).takeLastWhile(callbackAsFail2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
            },)
            describe("boolean callbacks", () => {
                describe.each(trueCallbacks,)("true: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeLastWhile(it,).toArray(),).toEqual(A,),)
                    test("2 fields", () => expect(new instance(AB,).takeLastWhile(it,).toArray(),).toEqual(AB,),)
                    test("4 fields", () => expect(new instance(ABCD,).takeLastWhile(it,).toArray(),).toEqual(ABCD,),)
                },)
                describe.each(falseCallbacks,)("false: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeLastWhile(it,),).toBeEmpty(),)
                    test("2 fields", () => expect(new instance(AB,).takeLastWhile(it,),).toBeEmpty(),)
                    test("4 fields", () => expect(new instance(ABCD,).takeLastWhile(it,),).toBeEmpty(),)
                },)
            },)
            describe("1 field", () => {
                test('a', () => expect(new instance(A,).takeLastWhile(callbackIsOverA,),).toBeEmpty(),)
                test('e', () => expect(new instance(A,).takeLastWhile(callbackIsOverE,),).toBeEmpty(),)
                test('0', () => expect(new instance(A,).takeLastWhile(callbackIsOver0Alt,),).toBeEmpty(),)
                test('4', () => expect(new instance(A,).takeLastWhile(callbackIsOver4Alt,),).toBeEmpty(),)
            },)
            describe("2 fields", () => {
                test('a', () => expect(new instance(AB,).takeLastWhile(callbackIsOverA,).toArray(),).toEqual(B,),)
                test('b', () => expect(new instance(AB,).takeLastWhile(callbackIsOverB,),).toBeEmpty(),)
                test('e', () => expect(new instance(AB,).takeLastWhile(callbackIsOverE,),).toBeEmpty(),)
                test('0', () => expect(new instance(AB,).takeLastWhile(callbackIsOver0Alt,).toArray(),).toEqual(B,),)
                test('1', () => expect(new instance(AB,).takeLastWhile(callbackIsOver1Alt,),).toBeEmpty(),)
                test('4', () => expect(new instance(AB,).takeLastWhile(callbackIsOver4Alt,),).toBeEmpty(),)
            },)
            describe("4 fields", () => {
                test('a', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOverA,).toArray(),).toEqual(BCD),)
                test('b', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOverB,).toArray(),).toEqual(CD,),)
                test('c', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOverC,).toArray(),).toEqual(D,),)
                test('d', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOverD,),).toBeEmpty(),)
                test('e', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOverE,),).toBeEmpty(),)
                test('0', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOver0Alt,).toArray(),).toEqual(BCD),)
                test('1', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOver1Alt,).toArray(),).toEqual(CD,),)
                test('2', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOver2Alt,).toArray(),).toEqual(D,),)
                test('3', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOver3Alt,),).toBeEmpty(),)
                test('4', () => expect(new instance(ABCD,).takeLastWhile(callbackIsOver4Alt,),).toBeEmpty(),)
            },)
        },)
        describe("takeLastWhileIndexed", () => {
            describe("empty", () => {
                test("0 arguments", () => expect(new instance(EMPTY,).takeLastWhileIndexed(callbackAsFail0,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("1 argument",  () => expect(new instance(EMPTY,).takeLastWhileIndexed(callbackAsFail1,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
                test("2 arguments", () => expect(new instance(EMPTY,).takeLastWhileIndexed(callbackAsFail2,),).toEqual(CollectionConstants.EMPTY_COLLECTION_HOLDER,),)
            },)
            describe("boolean callbacks", () => {
                describe.each(trueCallbacks,)("true: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeLastWhileIndexed(it,).toArray(),).toEqual(A,),)
                    test("2 fields", () => expect(new instance(AB,).takeLastWhileIndexed(it,).toArray(),).toEqual(AB,),)
                    test("4 fields", () => expect(new instance(ABCD,).takeLastWhileIndexed(it,).toArray(),).toEqual(ABCD,),)
                },)
                describe.each(falseCallbacks,)("false: %s", ({value: it,},) => {
                    test("1 field",  () => expect(new instance(A,).takeLastWhileIndexed(it,).toArray(),).toEqual(EMPTY,),)
                    test("2 fields", () => expect(new instance(AB,).takeLastWhileIndexed(it,).toArray(),).toEqual(EMPTY,),)
                    test("4 fields", () => expect(new instance(ABCD,).takeLastWhileIndexed(it,).toArray(),).toEqual(EMPTY,),)
                },)
            },)
            describe("1 field", () => {
                test('a', () => expect(new instance(A,).takeLastWhileIndexed(callbackIsOverAAlt,),).toBeEmpty(),)
                test('e', () => expect(new instance(A,).takeLastWhileIndexed(callbackIsOverEAlt,),).toBeEmpty(),)
                test('0', () => expect(new instance(A,).takeLastWhileIndexed(callbackIsOver0,),).toBeEmpty(),)
                test('4', () => expect(new instance(A,).takeLastWhileIndexed(callbackIsOver4,),).toBeEmpty(),)
            },)
            describe("2 fields", () => {
                test('a', () => expect(new instance(AB,).takeLastWhileIndexed(callbackIsOverAAlt,).toArray(),).toEqual(B,),)
                test('b', () => expect(new instance(AB,).takeLastWhileIndexed(callbackIsOverBAlt,),).toBeEmpty(),)
                test('e', () => expect(new instance(AB,).takeLastWhileIndexed(callbackIsOverEAlt,),).toBeEmpty(),)
                test('0', () => expect(new instance(AB,).takeLastWhileIndexed(callbackIsOver0,).toArray(),).toEqual(B,),)
                test('1', () => expect(new instance(AB,).takeLastWhileIndexed(callbackIsOver1,),).toBeEmpty(),)
                test('4', () => expect(new instance(AB,).takeLastWhileIndexed(callbackIsOver4,),).toBeEmpty(),)
            },)
            describe("4 fields", () => {
                test('a', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOverAAlt,).toArray(),).toEqual(BCD,),)
                test('b', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOverBAlt,).toArray(),).toEqual(CD,),)
                test('c', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOverCAlt,).toArray(),).toEqual(D,),)
                test('d', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOverDAlt,),).toBeEmpty(),)
                test('e', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOverEAlt,),).toBeEmpty(),)
                test('0', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOver0,).toArray(),).toEqual(BCD,),)
                test('1', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOver1,).toArray(),).toEqual(CD,),)
                test('2', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOver2,).toArray(),).toEqual(D,),)
                test('3', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOver3,),).toBeEmpty(),)
                test('4', () => expect(new instance(ABCD,).takeLastWhileIndexed(callbackIsOver4,),).toBeEmpty(),)
            },)
        },)
    },)

},)
