//··························································
// Copyright (c) 2023-2026. Jonathan Bédard ~ JóôòKiwi
//
// This project is free to use.
// All the right is reserved to the author of this project.
// My projects:
//  - https://github.com/joooKiwi/type
//  - https://github.com/joooKiwi/lazy
//  - https://github.com/joooKiwi/collection
//  - https://github.com/joooKiwi/enumeration
//··························································

import {CollectionHolder_AdaptorOfArrayFollower}                                                           from "./instance/CollectionHolder_AdaptorOfArray.follower"
import {CollectionHolder_ArrayOf1Follower}                                                                 from "./instance/CollectionHolder_ArrayOf1.follower"
import {CollectionHolder_ArrayOf2Follower}                                                                 from "./instance/CollectionHolder_ArrayOf2.follower"
import {CollectionHolder_1Follower}                                                                        from "./instance/CollectionHolder_1.follower"
import {CollectionHolder_2Follower}                                                                        from "./instance/CollectionHolder_2.follower"
import {CollectionHolder_ByViewerFollower}                                                                 from "./instance/CollectionHolder_ByViewer.follower"
import {CollectionHolder_ByGenericCollectionFollower}                                                      from "./instance/CollectionHolder_ByGenericCollection.follower"
import {CollectionHolder_AdaptorOfIteratorFollower}                                                        from "./instance/CollectionHolder_AdaptorOfIterator.follower"
import {CollectionHolder_AdaptorOfJsIteratorFollower}                                                      from "./instance/CollectionHolder_AdaptorOfJsIterator.follower"
import {CollectionHolder_AdaptorOfJsIterableFollower}                                                      from "./instance/CollectionHolder_AdaptorOfJsIterable.follower"
import {CollectionHolder_LazyFollower}                                                                     from "./instance/CollectionHolder_Lazy.follower"
import {CollectionHolder_LazyOf0Or1Follower}                                                               from "./instance/CollectionHolder_LazyOf0Or1.follower"
import {CollectionHolder_LazyOf0Or1Or2Follower}                                                            from "./instance/CollectionHolder_LazyOf0Or1Or2.follower"
import {CollectionHolder_LazyOf1Follower}                                                                  from "./instance/CollectionHolder_LazyOf1.follower"
import {CollectionHolder_LazyOf1Or2Follower}                                                               from "./instance/CollectionHolder_LazyOf1Or2.follower"
import {CollectionHolder_LazyOf2Follower}                                                                  from "./instance/CollectionHolder_LazyOf2.follower"
import {CollectionHolder_AdaptorOfMinimalistFollower}                                                      from "./instance/CollectionHolder_AdaptorOfMinimalist.follower"
import {CollectionHolder_AdaptorOfSetFollower}                                                             from "./instance/CollectionHolder_AdaptorOfSet.follower"
import {CollectionHolder_SetOf1Follower}                                                                   from "./instance/CollectionHolder_SetOf1.follower"
import {CollectionHolder_SetOf2Follower}                                                                   from "./instance/CollectionHolder_SetOf2.follower"
import {every0Instances, every1Instances, every2Instances, everyExtensionMethodInstances, everyNInstances} from "./value/instances"

import {EmptyCollectionHolder} from "../src/EmptyCollectionHolder"

describe("CollectionHolderTest (size)", () => {

    describe("EmptyCollectionHolder", () => {
        const instance = EmptyCollectionHolder.get

        test("size",                      () => expect(instance.size,).toBe(0,),)
        test("length",                    () => expect(instance.length,).toBe(0,),)
        test("count",                     () => expect(instance.count,).toBe(0,),)
        test("isEmpty",                   () => expect(instance.isEmpty,).toBeTrue(),)
        test("isNotEmpty",                () => expect(instance.isNotEmpty,).toBeFalse(),)
        test("hasAtLeast1Element",        () => expect(instance.hasAtLeast1Element,).toBeFalse(),)
        test("containsAtLeast1Element",   () => expect(instance.containsAtLeast1Element,).toBeFalse(),)
        test("includesAtLeast1Element",   () => expect(instance.includesAtLeast1Element,).toBeFalse(),)
        test("hasExactly1Element",        () => expect(instance.hasExactly1Element,).toBeFalse(),)
        test("containsExactly1Element",   () => expect(instance.containsExactly1Element,).toBeFalse(),)
        test("includesExactly1Element",   () => expect(instance.includesExactly1Element,).toBeFalse(),)
        test("hasAtMost1Element",         () => expect(instance.hasAtMost1Element,).toBeTrue(),)
        test("containsAtMost1Element",    () => expect(instance.containsAtMost1Element,).toBeTrue(),)
        test("includesAtMost1Element",    () => expect(instance.includesAtMost1Element,).toBeTrue(),)
        test("hasAtLeast2Elements",       () => expect(instance.hasAtLeast2Elements,).toBeFalse(),)
        test("containsAtLeast2Elements",  () => expect(instance.containsAtLeast2Elements,).toBeFalse(),)
        test("includesAtLeast2Elements",  () => expect(instance.includesAtLeast2Elements,).toBeFalse(),)
        test("hasExactly2Elements",       () => expect(instance.hasExactly2Elements,).toBeFalse(),)
        test("containsExactly2Elements",  () => expect(instance.containsExactly2Elements,).toBeFalse(),)
        test("includesExactly2Elements",  () => expect(instance.includesExactly2Elements,).toBeFalse(),)
        test("hasAtMost2Elements",        () => expect(instance.hasAtMost2Elements,).toBeTrue(),)
        test("containsAtMost2Elements",   () => expect(instance.containsAtMost2Elements,).toBeTrue(),)
        test("includesAtMost2Elements",   () => expect(instance.includesAtMost2Elements,).toBeTrue(),)
    },)

    describe("aliases", () => {
        describe("ArrayAsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfArrayFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("ArrayOf1AsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_ArrayOf1Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("ArrayOf2AsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_ArrayOf2Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("CollectionHolderOf1", () => {
            test("length",                   () => expect(new CollectionHolder_1Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_1Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_1Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_1Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_1Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_1Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_1Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_1Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_1Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_1Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_1Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_1Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_1Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_1Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_1Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("CollectionHolderOf2", () => {
            test("length",                   () => expect(new CollectionHolder_2Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_2Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_2Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_2Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_2Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_2Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_2Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_2Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_2Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_2Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_2Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_2Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_2Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_2Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_2Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("CollectionViewer", () => {
            test("length",                   () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_ByViewerFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("GenericCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_ByGenericCollectionFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("IteratorAsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfIteratorFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("JsIterableAsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfJsIterableFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("JsIteratorAsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfJsIteratorFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("LazyCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_LazyFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_LazyFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_LazyFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_LazyFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_LazyFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_LazyFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_LazyFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_LazyFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_LazyFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_LazyFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_LazyFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_LazyFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_LazyFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_LazyFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_LazyFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("LazyCollectionHolderOf0Or1", () => {
            test("length",                   () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_LazyOf0Or1Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("LazyCollectionHolderOf0Or1Or2", () => {
            test("length",                   () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_LazyOf0Or1Or2Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("LazyCollectionHolderOf1", () => {
            test("length",                   () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_LazyOf1Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("LazyCollectionHolderOf1Or2", () => {
            test("length",                   () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_LazyOf1Or2Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("LazyCollectionHolderOf2", () => {
            test("length",                   () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_LazyOf2Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("MinimalistAsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfMinimalistFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("SetAsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_AdaptorOfSetFollower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("SetOf1AsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_SetOf1Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
        describe("SetOf2AsCollectionHolder", () => {
            test("length",                   () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.length,)                  .size_amountOfCall,)               .toBe(1,),)
            test("count",                    () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.count,)                   .size_amountOfCall,)               .toBe(1,),)
            test("hasAtLeast1Element",       () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.hasAtLeast1Element,)      .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsAtLeast1Element",  () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.containsAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("includesAtLeast1Element",  () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.includesAtLeast1Element,) .isNotEmpty_amountOfCall,)         .toBe(1,),)
            test("containsExactly1Element",  () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.containsExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("includesExactly1Element",  () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.includesExactly1Element,) .hasExactly1Element_amountOfCall,) .toBe(1,),)
            test("containsAtMost1Element",   () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.containsAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("includesAtMost1Element",   () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.includesAtMost1Element,)  .hasAtMost1Element_amountOfCall,)  .toBe(1,),)
            test("containsAtLeast2Elements", () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.containsAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("includesAtLeast2Elements", () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.includesAtLeast2Elements,).hasAtLeast2Elements_amountOfCall,).toBe(1,),)
            test("containsExactly2Elements", () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.containsExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("includesExactly2Elements", () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.includesExactly2Elements,).hasExactly2Elements_amountOfCall,).toBe(1,),)
            test("containsAtMost2Elements",  () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.containsAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
            test("includesAtMost2Elements",  () => expect(new CollectionHolder_SetOf2Follower().execute(it => it.includesAtMost2Elements,) .hasAtMost2Elements_amountOfCall,) .toBe(1,),)
        },)
    },)

    describe("methods", () => {
    describe.each(everyExtensionMethodInstances,)("%s", ({value: {instance,},},) => {
        test("isEmpty",    () => expect(instance.isEmpty,)   .toBeTrue(),)
        test("isNotEmpty", () => expect(instance.isNotEmpty,).toBeFalse(),)
    },)},)

    describe("instances", () => {
        describe("empty", () => {
            describe.each(every0Instances,)("%s", ({value: {newInstance,},},) => {
                test("size",       () => expect(newInstance().size,)      .toBe(0,),)
                test("isEmpty",    () => expect(newInstance().isEmpty,)   .toBeTrue(),)
                test("isNotEmpty", () => expect(newInstance().isNotEmpty,).toBeFalse(),)
            },)
        },)
        describe("1 field", () => {
            const value = Symbol("1 field: value",)
            describe.each(every1Instances,)("%s", ({value: {newInstance,},},) => {
                test("size",       () => expect(newInstance(value,).size,)      .toBe(1,),)
                test("isEmpty",    () => expect(newInstance(value,).isEmpty,)   .toBeFalse(),)
                test("isNotEmpty", () => expect(newInstance(value,).isNotEmpty,).toBeTrue(),)
            },)
        },)
        describe("2 fields", () => {
            const value2 = Symbol("2 fields: 1st value",)
            const value1 = Symbol("2 fields: 2nd value",)
            describe.each(every2Instances,)("%s", ({value: {newInstance,},},) => {
                test("size",       () => expect(newInstance(value1, value2,).size,)      .toBe(2,),)
                test("isEmpty",    () => expect(newInstance(value1, value2,).isEmpty,)   .toBeFalse(),)
                test("isNotEmpty", () => expect(newInstance(value1, value2,).isNotEmpty,).toBeTrue(),)
            },)
        },)
        describe("N fields", () => {
            const values = [
                Symbol("4 fields: 1st value",),
                Symbol("4 fields: 2nd value",),
                Symbol("4 fields: 3rd value",),
                Symbol("4 fields: 4th value",),
            ]
            describe.each(everyNInstances,)("%s", ({value: {instance,},},) => {
                test("size",       () => expect(new instance(values,).size,)      .toBe(4,),)
                test("isEmpty",    () => expect(new instance(values,).isEmpty,)   .toBeFalse(),)
                test("isNotEmpty", () => expect(new instance(values,).isNotEmpty,).toBeTrue(),)
            },)
        },)
    },)

},)
